document.addEventListener('DOMContentLoaded', function() {

    // --- BASE DE DATOS DE CANCIONES COMPLETA CON CLASIFICACIÓN ---
    const songsData = {
        "1951": ["1. Nilla Pizzi – Grazie dei ﬁori", "2. Nilla Pizzi y Achille Togliani – La luna si veste d’argento", "3. Achille Togliani – Serenata a nessuno", "4. Achille Togliani y Duo Fasano – Al mercato di Pizzighettone", "5. Duo Fasano – La cicogna distratta", "6. Nilla Pizzi y Duo Fasano – La margherita", "7. Nilla Pizzi y Achille Togliani – L’eco fra gli abeti", "8. Achille Togliani y Duo Fasano – Togliani Famme durmì", "9. Achille Togliani – Sedici anni", "10. Duo Fasano – Sotto il mandorlo", "- Nilla Pizzi – È l’alba", "- Achille Togliani – Mai più", "- Achille Togliani y Duo Fasano – Sei fatta per me", "- Duo Fasano – Sorrentinella", "- Nilla Pizzi – Tutto è ﬁnito", "- Nilla Pizzi – Ho pianto una volta sola", "- Achille Togliani – Mani che si cercano", "- Nilla Pizzi – Mia cara Napoli", "- Nilla Pizzi – Notte di Sanremo", "- Nilla Pizzi – Oro di Napoli"],
        "1952": ["1. Nilla Pizzi – Vola colomba", "2. Nilla Pizzi – Papaveri e papere", "3. Nilla Pizzi – Una donna prega", "4. Oscar Carboni – Madonna delle rose", "5. Gino Latilla – Un disco dall’Italia", "6. Gino Latilla – L’attesa", "7. Oscar Carboni – Perché le donne belle", "8. Achille Togliani – Vecchie mura", "9. Achille Togliani – Libro di novelle", "10. Nilla Pizzi y Achille Togliani – Nel regno dei sogni", "- Duo Fasano – Al ritmo della carrozzella", "- Achille Togliani – La collanina", "- Gino Latilla – Pura fantasia", "- Nilla Pizzi – Ninna nanna ai sogni perduti", "- Nilla Pizzi y Duo Fasano – Il valzer di nonna Speranza", "- Duo Fasano – Due gattini", "- Gino Latilla – Malinconica tarantella", "- Nilla Pizzi y Duo Fasano – Buonanotte ai bimbi del mondo", "- Oscar Carboni – Cantate e sorridete", "- Duo Fasano – Vecchio tram"],
        "1953": ["1. Carla Boni / Flo Sandon’s – Viale d’autunno", "2. Nilla Pizzi y Doppio Quintetto Vocale / Teddy Reno y Quartetto Star - Campanaro", "3. Giorgio Consolini / Gino Latilla & Doppio Quintetto Vocale – Vecchio scarpone", "4. Achille Togliani / Teddy Reno – Lasciami cantare una canzone", "5. Gino Latilla / Giorgio Consolini – Vecchia villa comunale", "6. Achille Togliani / Katyna Ranieri – No, Pierrot", "7. Carla Boni / Quartetto Star – Il passerotto", "8. Nilla Pizzi y Doppio Quintetto Vocale / Teddy Reno y Quartetto Star – Sussurrando buonanotte", "9. Gino Latilla y Doppio Quintetto Vocale / Giorgio Consolini – Tamburino del reggimento", "10. Nilla Pizzi y Doppio Quintetto Vocale / Teddy Reno y Quartetto Star – Papà paciﬁco", "- Nilla Pizzi / Teddy Reno – Canto della solitudine", "- Gino Latilla / Teddy Reno – Innamorarmi", "- Achille Togliani / Katyna Ranieri – La pianola stonata", "- Gino Latilla / Giorgio Consolini – Povero amico mio", "- Carla Boni / Flo Sandon’s – Qualcuno cammina", "- Carla Boni / Katyna Ranieri – Acque amare", "- Carla Boni / Flo Sandon’s – Buona sera", "- Achille Togliani / Katyna Ranieri – Domandatelo", "- Giorgio Consolini / Achille Togliani – La mamma che piange di più", "- Nilla Pizzi / Flo Sandon’s – L’altra"],
        "1954": ["1. Gino Latilla / Giorgio Consolini – Tutte le mamme", "2. Katyna Ranieri / Achille Togliani – Canzone da due soldi", "3. Gino Latilla / Franco Ricci – …E la barca tornò sola", "4. Vittoria Mongardi / Natalino Otto – Notturno… (per chi non ha nessuno)", "5. Carla Boni / Flo Sandon’s – Non è mai troppo tardi", "6. Vittoria Mongardi y Duo Fasano / Quartetto Cetra – Aveva un bavero", "7. Gino Latilla y Duo Fasano / Katyna Ranieri & Giorgio Consolini – Sotto l’ombrello", "8. Achille Togliani / Natalino Otto – Mogliettina", "9. Achille Togliani / Flo Sandon’s – Con te", "10. Natalino Otto / Achille Togliani – Donnina sola", "- Vittoria Mongardi / Flo Sandon’s – Angeli senza cielo", "- Carla Boni y Gino Latilla / Quartetto Cetra – Arriva il direttore", "- Carla Boni y Duo Fasano / Giorgio Consolini – Berata ﬁlava", "- Quartetto Cetra / Gino Latilla y Duo Fasano – Piripicchio e Piripicchia", "- Natalino Otto / Gino Latilla – Una bambina sei tu", "- Gino Latilla y Duo Fasano / Quartetto Cetra – Canzoni alla sbarra", "- Carla Boni y Duo Fasano / Quartetto Cetra – Cirillino ci", "- Achille Togliani / Gianni Ravera – Gioia di vivere", "- Vittoria Mongardi / Katyna Ranieri – Rose (Oggi i tempi son cambiati)", "- Carla Boni / Quartetto Cetra – Un diario"],
        "1955": ["1. Claudio Villa / Tullio Pane – Buongiorno tristezza", "2. Claudio Villa / Tullio Pane – Il torrente", "3. Natalino Otto y Trio Aurora / Nuccia Bongiovanni, Bruno Pallesi y Radio Boys – Canto nella valle", "4. Narciso Parigi / Claudio Villa – Incantatella", "5. Antonio Basurto / Gianni Ravera – Un cuore", "6. Jula De Palma / Marisa Colomber – L’ombra", "7. Natalino Otto y Trio Aurora / Narciso Parigi y Radio Boys – Ci ciu ci (cantava un usignol)", "8. Antonio Basurto / Natalino Otto – Una fotograﬁa nella cornice", "- Antonio Basurto / Jula De Palma – Cantilena del trainante", "- Clara Jaione y Radio Boys / Bruno Rosettani y Trio Aurora – Zucchero e pepe", "- Jula De Palma / Bruno Pallesi – Sentiero", "- Nuccia Bongiovanni y Bruno Pallesi / Nella Colombo, Bruno Rosettani y Trio Aurora – Il primo viaggio", "- Gianni Ravera / Tullio Pane – Non penserò che a te", "- Jula De Palma / Bruno Pallesi – Che fai tu luna in ciel", "- Clara Jaione y Radio Boys / Nella Colombo & Bruno Rosettani y Trio Aurora – Era un omino (piccino piccino)", "- Natalino Otto / Nuccia Bongiovanni y Radio Boys – I tre timidi"],
        "1956": ["1. Franca Raimondi – Aprite le ﬁnestre", "2. Tonina Torrielli – Amami se vuoi", "3. Luciana Gonzales – La vita è un paradiso di bugie", "4. Tonina Torrielli – Il cantico del cielo", "5. Ugo Molinari – La colpa fu", "6. Tonina Torrielli / Katyna Ranieri – Il bosco innamorato", "7. Ugo Molinari – Albero caduto", "8. Gianni Marzocchi – Musetto (la più bella sei tu)", "9. Ugo Molinari – Nota per nota", "10. Ugo Molinari – Due teste sul cuscino", "- Gianni Marzocchi y Clara Vincenzi – Anima gemella", "- Luciana Gonzales – È bello", "- Gianni Marzocchi – Ho detto al sole", "- Franca Raimondi – Il trenino del destino", "- Clara Vincenzi – Il trenino di latta verde", "- Gianni Marzocchi y Franca Raimondi – Lucia e Tobia", "- Clara Vincenzi – Lui e lei", "- Luciana Gonzales – Parole e musica", "- Franca Raimondi y Clara Vincenzi – Sogni d’or", "- Tonina Torrielli – Qualcosa è rimasto"],
        "1957": ["1. Claudio Villa / Nunzio Gallo – Corde della mia chitarra", "2. Claudio Villa / Giorgio Consolini – Usignolo", "3. Gino Latilla / Tonina Torrielli – Scusami", "4. Carla Boni, Gino Latilla y Duo Fasano / Gloria, Christian y Poker di Voci – Casetta in Canadà", "5. Giorgio Consolini / Claudio Villa – Cancello tra le rose", "6. Natalino Otto y Poker di Voci / Gino Latilla y Claudio Villa – Il pericolo numero uno", "7. Tina Allori / Tonina Torrielli – Intorno a te (è sempre primavera)", "8. Carla Boni / Nunzio Gallo – Per una volta ancora", "9. Gino Latilla y Duo Fasano / Natalino Otto y Poker di Voci – Un ﬁlo di speranza", "10. Carla Boni y Duo Fasano / Gloria Christian, Natalino Otto y Poker di Voci – Le trote blu", "- Fiorella Bini / Flo Sandon’s – Estasi", "- Gino Baldi / Luciano Virgili – Finalmente", "- Gino Latilla / Nunzio Gallo – Non ti ricordi più?", "- Natalino Otto / Gianni Ravera – Un certo sorriso", "- Carla Boni / Jula De Palma – Un sogno di cristallo", "- Gino Latilla / Luciano Virgili – A poco a poco", "- Tina Allori / Flo Sandon’s – Ancora ci credo", "- Gino Baldi / Jula De Palma – Nel giardino del mio cuore", "- Fiorella Bini y Duo Fasano / Jula De Palma y Poker di Voci – Raggio nella nebbia"],
        "1958": ["1. Domenico Modugno / Johnny Dorelli – Nel blu dipinto di blu", "2. Nilla Pizzi / Tonina Torrielli – L’edera", "3. Gino Latilla / Nilla Pizzi – Amare un’altra", "4. Giorgio Consolini / Claudio Villa – Campana di Santa Lucia", "5. Nilla Pizzi / Claudio Villa – Giuro d’amarti così", "6. Carla Boni y Gino Latilla / Aurelio Fierro y Gloria Christian – Timida serenata", "7. Claudio Villa y Duo Fasano / Aurelio Fierro y Trio Joice – Fragole e cappellini", "8. Carla Boni y Gino Latilla / Natalino Otto – Non potrai dimenticare", "9. Cristina Jorio / Tonina Torrielli – Mille volte", "10. Johnny Dorelli / Natalino Otto – Fantastica", "- Carla Boni / Giorgio Consolini – Arsura", "- Trio Joice / Tonina Torrielli y Duo Fasano – Nozze d’oro", "- Gino Latilla / Natalino Otto – Tu sei del mio paese", "- Giorgio Consolini / Johnny Dorelli – Se tornassi tu…!", "- Giorgio Consolini / Marisa Del Frate – È molto facile dirsi addio", "- Claudio Villa y Duo Fasano / Nilla Pizzi y Aurelio Fierro – La canzone che piace a te", "- Duo Fasano y Tonina Torrielli / Aurelio Fierro y Trio Joice – I trulli di Alberobello", "- Carla Boni / Cristina Jorio – Io sono te", "- Claudio Villa y Gino Latilla / Gloria Christian – Cos’è un bacio", "- Gloria Christian / Marisa Del Frate – Ho disegnato un cuore"],
        "1959": ["1. Domenico Modugno / Johnny Dorelli – Piove (ciao ciao bambina)", "2. Gino Latilla / Arturo Testa – Io sono il vento", "3. Tedy Reno / Achille Togliani – Conoscerti", "4. Jula De Palma / Tonina Torrielli – Tua", "5. Aurelio Fierro / Teddy Reno – Lì per lì", "6. Fausto Cigliano / Nilla Pizzi – Sempre con te", "7. Natalino Otto / Aurelio Fierro – Avevamo la stessa età", "8. Betty Curtis / Wilma De Angelis – Nessuno", "9. Johnny Dorelli y Betty Curtis / Gino Latilla y Claudio Villa – Una marcia in fa", "10. Claudio Villa / Betty Curtis – Un bacio sulla bocca", "- Tonina Torrielli / Nilla Pizzi – Adorami", "- Anna D’Amico / Natalino Otto – Così così", "- Nilla Pizzi / Tonina Torrielli – Il nostro refrain", "- Jula De Palma / Miranda Martino – La vita mi ha dato solo te", "- Natalino Otto / Gino Latilla – La luna è un’altra luna", "- Teddy Reno / Achille Togliani – Ma baciami", "- Arturo Testa / Fausto Cigliano – Né stelle né mare", "- Claudio Villa / Johnny Dorelli – Partir con te", "- Wilma De Angelis / Jula De Palma – Per tutta la vita", "- Achille Togliani / Arturo Testa – Tu sei qui"],
        "1960": ["1. Tony Dallara / Renato Rascel – Romantica", "2. Domenico Modugno / Teddy Reno – Libero", "3. Wilma De Angelis / Joe Sentieri – Quando vien la sera", "4. Nilla Pizzi / Tonina Torrielli – Colpevole", "5. Joe Sentieri / Sergio Bruni – È mezzanotte", "6. Giorgio Consolini / Sergio Bruni – Il mare", "7. Jula De Palma / Tony Dallara – Noi", "8. Teddy Reno / Mina – È vero", "9. Fausto Cigliano / Irene D’Areni – Splende il sole", "10. Johnny Dorelli / Jula De Palma – Notte mia", "- Flo Sandon’s / Gloria Christian – “A” come amore", "- Achille Togliani / Giorgio Consolini – Amore abisso dolce", "- Johnny Dorelli / Betty Curtis – Amore senza sole", "- Germana Caroli / Arturo Testa – Gridare di gioia", "- Gino Latilla / Miranda Martino – Invoco te", "- Mina / Betty Curtis – Non sei felice", "- Tonina Torrielli / Arturo Testa – Perderti", "- Achille Togliani / Nilla Pizzi – Perdoniamoci", "- Wilma De Angelis / Gloria Christian – Splende l’arcobaleno", "- Gino Latilla / Miranda Martino – Vento, pioggia… scarpe rotte"],
        "1961": ["1. Betty Curtis / Luciano Tajoli – Al di là", "2. Adriano Celentano / Little Tony – 24 mila baci", "3. Milva / Gino Latilla – Il mare nel cassetto", "4. Mina / Nelly Fioramonti – Io amo tu ami", "5. Mina / Jenny Luna – Le mille bolle blu", "6. Pino Donaggio / Teddy Reno – Come sinfonia", "7. Arturo Testa / Tonina Torrielli – Febbre di musica", "8. Teddy Reno / Sergio Bruni – Mandolino mandolino", "9. Sergio Bruni / Rocco Granata – Carolina, dai", "10. Gino Paoli / Tony Dallara – Un uomo vivo", "11. Umberto Bindi / Miranda Martino – Non mi dire chi sei", "12. Joe Sentieri / Fausto Cigliano – Lei", "- Bruno Martino / Jula De Palma – A.A.A. Adorabile cercasi", "- Giorgio Gaber / Maria Monti – Benzina e cerini", "- Luciano Rondinella / Edoardo Vianello – Che freddo!", "- Miranda Martino / Jimmy Fontana – Lady luna", "- Joe Sentieri / Betty Curtis – Libellule", "- Claudio Villa / Sergio Renda – Mare di dicembre", "- Aura D’Angelo / Silvia Guidi – Notturno senza luna", "- Gianni Meccia / Wilma De Angelis – Patatina", "- Tony Renis / Niky Davis – Pozzanghere", "- Cocky Mazzetti / Achille Togliani – Qualcuno mi ama", "- Carla Boni / Aurelio Fierro – Tu con me", "- Nadia Liani / Jolanda Rossin – Una goccia di cielo"],
        "1962": ["1. Domenico Modugno / Claudio Villa – Addio… addio…", "2. Sergio Bruni / Milva – Tango italiano", "3. Sergio Bruni / Ernesto Bonino – Gondolì gondolà", "4. Tony Renis / Emilio Pericoli – Quando quando quando", "5. Milva / Miriam Del Mare – Stanotte al luna park", "6. Gino Bramieri / Aurelio Fierro – Lui andava a cavallo", "7. Arturo Testa / Jolanda Rossin – Un’anima leggera", "8. Joe Sentieri / Aurelio Fierro – Cipria di sole", "9. Tonina Torrielli / Aura D’Angelo – Aspettandoti", "10. Johnny Dorelli / Betty Curtis – Buongiorno amore", "11. Flo Sandon’s / Mario D’Alba – Passa il tempo", "12. Nunzio Gallo / Rocco Montana – Inventiamo la vita", "- Arturo Testa / Jolanda Rossin – Centomila volte", "- Wilma De Angelis / Tanya – I colori della felicità", "- Johnny Dorelli / Gloria Christian – L’ombrellone", "- Nunzio Gallo / Bruna Lelli – L’ultimo pezzo di terra", "- Mario Abbate / Fausto Cigliano – Vestita di rosso", "- Gino Bramieri / Giacomo Rondinella – Pesca tu che pesco anch’io", "- Wilma De Angelis / Lucia Altieri – Lumicini rossi", "- Corrado Lojacono / Luciano Tajoli – L’anellino", "- Nelly Fioramonti / Claudio Villa – Quando il vento d’aprile", "- Jenny Luna / Silvia Guidi – Conta le stelle", "- Lucia Altieri / Gian Costello – Due cipressi", "- Pierﬁlippi / Cocky Mazzetti – Occhi senza lacrime", "- Wanda Romanelli / Silvia Guidi – Fiori sull’acqua", "- Fausto Cigliano / Jenny Luna – Cose inutili", "- Gesy Sebena / Giacomo Rondinella – Il nostro amore", "- Cocky Mazzetti / Joe Sentieri – Tobia", "- Narciso Parigi / Giorgio Consolini – Vita", "- Luciano Tajoli / Betty Curtis – Il cielo cammina", "- Gene Colonnello / Gloria Christian – Innamorati", "- Nelly Fioramonti / Edda Montanari – Prima del paradiso"],
        "1963": ["1. Tony Renis/ Emilio Pericoli - Uno per tutte", "2. Claudio Villa/ Eugenia Foligatti - Amor, mon amour, my love", "3. Pino Donaggio/ Cocky Mazzetti - Giovane giovane", "4. Johnny Dorelli/ Wilma De Angelis - Non costa niente", "5. Milva/ Luciano Tajoli - Ricorda", "6. Tonina Torrielli/ Eugenia Foligatti - Perdonarsi in due", "7. Claudio Villa/ Aurelio Fierro - Occhi neri e cielo blu", "8. Emilio Pericoli/ Sergio Bruni - Sull’acqua", "9. Aura D’angelo/ Arturo Testa - Tu venisti dal mare", "10. Milva/ Gianni Lacommare - Non sapevo", "- Joe Sentieri/ Johnny Dorelli - Fermate il mondo", "- Luciano Tajoli/ Ennio Sangiusto - Le voci", "- Mario Abbate/ Quartetto Radar - Oggi non ho tempo", "- Tony Renis/ Cocky Mazzetti - Perché, perché", "- Flo Sandon’s/ Wilma De Angelis - Se passerai di qui", "- Gianni Lacommare/ Tonina Torrielli - Com’è piccolo il cielo", "- Quartetto Radar/ Ennio Sangiusto - La ballata del pedone", "- Joe Sentieri/ Arturo Testa - Quando ci si vuol bene… (come noi)", "- Aurelio Fierro/ Sergio Bruni - Un cappotto rivoltato", "- Mario Abbate/ Flo Sandon’s - Vorrei fermare il tempo"],
        "1964": ["1. Gigliola Cinquetti / Patricia Carli – Non ho l'età (Per amarti)", "- Domenico Modugno / Frankie Laine – Che me ne importa a me", "- Tony Dallara / Ben E. King - Come potrei domenticarti", "- Gino Paoli / Antonio Prieto – Ieri ho incontrato mia madre", "- Fabrizio Ferretti / Gil Fields & The Fraternity Brothers – La prima che incontro", "- Pino Donaggio / Frankie Avalon – Motivo d'amore", "- Roby Ferrante / Paul Anka – Ogni volta", "- Little Tony / Gene Pitney – Quando vedrai la mia ragazza", "- Bruno Filippini / Gil Fields & The Fraternity Brothers – Sabato sera", "- Remo Germani / Nino Tempo & April Stevens – Stasera no no no", "- Robertino / Bobby Rydell – Un bacio piccolissimo", "- Bobby Solo / Frankie Laine – Una lacrima sul viso", "- Giorgio Gaber / Patricia Carli – Così felice", "- Fausto Cigliano / Gene Pitney – E se domani", "- Tony Renis / Frankie Avalon – I sorrisi di sera", "- Piero Focaccia / Bobby Rydell – L'inverno cosa fai?", "- Milva / Frida Boccara – L'ultimo tram", "- Cocky Mazzetti / Los Hermanos Rigual – Mezzanotte", "- Claudio Villa / Peggy March – Passo su passo", "- Emilio Pericoli / Peter Kraus – Piccolo piccolo", "- Aurelio Fierro / Marina Moran – Sole pizza e amore", "- Laura Villa / Los Hermanos Rigual – Sole sole", "- Lilly Bonato / Richard Moser jr. – Tu piangi per niente", "- Nicola Arigliano / Peter Kraus – Venti chilometri al giorno"],
        "1965": ["1. Bobby Solo / The New Christy Minstrels – Se piangi, se ridi", "- Ornella Vanoni / Udo Jürgens – Abbracciami forte", "- Nicola Di Bari / Gene Pitney – Amici miei", "- Fred Bongusto / Kiki Dee – Aspetta domani", "- Gigliola Cinquetti / Connie Francis – Ho bisogno di vederti", "- Betty Curtis / Petula Clark – Invece no", "- Pino Donaggio / Jody Miller – Io che non vivo (senza te)", "- Bruno Filippini / Yukari Ito – L'amore ha i tuoi occhi", "- Wilma Goich / The New Christy Minstrels – Le colline sono in ﬁore", "- Remo Germani / Le Amiche – Prima o poi", "- Vittorio Inzaina / Les Surfs – Si vedrà", "- Milva / Bernd Spier – Vieni con noi", "- John Foster / Joe Damiano – Cominciamo ad amarci", "- Ricky Gianco / Jody Miller – Devi essere tu", "- Gianni Mascolo / Dusty Springﬁeld – Di fronte all'amore", "- Don Miko / Timi Yuro – E poi verrà l'autunno", "- Iva Zanicchi / Gene Pitney – I tuoi anni più belli", "- Bruno Lauzi / Kenny Rankin – Il tuo amore", "- Giordano Colombo / Hoagy Lands – Io non volevo", "- Beppe Cardile / Anita Harris – L'amore è partito", "- Robertino / Danyel Gérard – Mia cara", "- Franco Tozzi / Johnny Tillotson – Non a caso il destino (Ci ha fatto incontrare)", "- Peppino Gagliardi / Timi Yuro – Ti credo", "- Fabrizio Ferretti / Dusty Springﬁeld – Tu che ne sai?"],
        "1966": ["1. Domenico Modugno / Gigliola Cinquetti – Dio, come ti amo", "2. Caterina Caselli / Gene Pitney – Nessuno mi può giudicare", "3. Wilma Goich / Les Surfs – In un ﬁore", "4. Pino Donaggio / Claudio Villa – Una casa in cima al mondo", "5. Anna Identici / The New Christy Minstrels – Una rosa da Vienna", "6. Orietta Berti / Ornella Vanoni – Io ti darò di più", "7. Giorgio Gaber / Pat Boone – Mai mai mai Valentina", "8. Edoardo Vianello / Françoise Hardy – Parlami di te", "9. Sergio Endrigo / Chad & Jeremy – Adesso sì", "10. Milva / Richard Anthony – Nessuno di voi", "11. Peppino Gagliardi / Pat Boone – Se tu non fossi qui", "12. Remo Germani / Les Surfs – Così come viene", "13. Iva Zanicchi / Vic Dana – La notte dell'addio", "14. I Ribelli / The New Christy Minstrels – A la buena de Dios", "- Luciana Turina / Gino – Dipendesse da me", "- Adriano Celentano / Trio del Clan – Il ragazzo della via Gluck", "- Franco Tozzi / Bobby Vinton – Io non posso crederti", "- Anna Marchetti / Plinio Maggi – Io ti amo", "- Gino Paoli / Ricardo – La carta vincente", "- Nicola Di Bari / Gene Pitney – Lei mi aspetta", "- Lucio Dalla / The Yardbirds – Paﬀf... bum", "- Giuseppe Di Stefano / P. J. Proby – Per questo voglio te", "- Luciano Tomei / Luis Alberto del Paraná & Los Paraguayos – Quando vado sulla riva", "- Bobby Solo / The Yardbirds – Questa volta", "- John Foster / Paola Bertoni – Se questo ballo non ﬁnisse mai", "- Equipe 84 / The Renegades – Un giorno tu mi cercherai"],
        "1967": ["1. Iva Zanicchi / Claudio Villa – Non pensare a me", "2. Annarita Spinaci / Les Surfs – Quando dico che ti amo", "3. I Giganti / The Bachelors – Proposta", "4. Ornella Vanoni / Mario Guarnera – La musica è ﬁnita", "5. Orietta Berti / Les compagnons de la Chanson – Io, tu e le rose", "6. Lucio Dalla / The Rokes – Bisogna saper perdere", "7. Sergio Endrigo / Memo Remigi – Dove credi di andare", "8. Gian Pieretti / Antoine – Pietre", "9. Johnny Dorelli / Don Backy – L'immensità", "10. Little Tony / Mario Zelinotti – Cuore matto", "11. Pino Donaggio / Carmen Villani – Io per amore", "12. Wilma Goich / The Bachelors – Per vedere quant'è grande il mondo", "13. Giorgio Gaber / Remo Germani – E allora dai", "14. Gianni Pettenati / Gene Pitney – La rivoluzione", "- Connie Francis / Bobby Solo – Canta ragazzina", "- Fred Bongusto / Anna German – Gi", "- Ricky Maiocchi / Marianne Faithfull – C’è chi spera", "- Mino Reitano / The Hollies – Non prego per me", "- Cher / Nico Fidenco – Ma piano (per non svegliarmi)", "- Domenico Modugno / Gidiuli – Sopra i tetti azzurri del mio pazzo amore", "- Los Marcellos Ferial / The Happenings – Quando vedrò", "- Luigi Tenco / Dalida – Ciao amore ciao", "- Peppino Di Capri / Dionne Warwick – Dedicato all’amore", "- Roberta Amadei / Carmelo Pagano – Devi aver ﬁducia in me", "- Tony Del Monaco / Betty Curtis – È più forte di me", "- Gene Pitney / Nicola Di Bari – Guardati alle spalle", "- Caterina Caselli / Sonny Bonno y Cher – Il cammino di ogni speranza", "- Jimmy Fontana / Edoardo Vianello – Nasce una vita", "- Milva / Los Bravos – Uno come noi", "- Donatella Moretti / Bobby Goldsboro – Una ragazza"],
        "1968": ["1. Sergio Endrigo / Roberto Carlos – Canzone per te", "2. Ornella Vanoni / Marisa Sannia – Casa bianca", "3. Adriano Celentano / Milva – Canzone", "4. Fausto Leali / Wilson Pickett – Deborah", "5. Gianni Pettenati / Antoine – La tramontana", "6. Anna Identici / The Sandpipers – Quando m’innamoro", "7. Massimo Ranieri / Il Giganti – Da bambino", "8. Gigliola Cinquetti / Giuliana Valci – Sera", "9. Al Bano / Bobbie Gentry – La siepe", "10. Little Tony / Mario Guarnera – Un uomo piange solo per amore", "11. Wilma Goich / Dino – Gli occhi miei", "12. Annarita Spinaci / Yoko Kishi – Stanotte sentirai una canzone", "13. Louis Armstrong / Lara Saint Paul – Mi va di cantare", "14. Tony Del Monaco / Dionne Warwick – La voce del silenzio", "- Peppino Gagliardi / Eartha Kitt – Che vale per me", "- Tony Renis / Domenico Modugno – Il posto mio", "- Pilade / Nino Ferrer – Il re d’Inghilterra", "- Johnny Dorelli / Paul Anka – La farfalla impazzita", "- Elio Gandolﬁ / Shirley Bassey – La vita", "- The Rokes / The Cowsills – Le opere di Bartolomeo", "- Pino Donaggio / Timi Yuro – Le solite cose", "- Giusy Romeo / Sacha Distel – No amore", "- Iva Zanicchi / Udo Jurgens – Per vivere", "- Orietta Berti / Piergiorgio Farina – Tu che non sorridi mai"],
        "1969": ["1. Bobby Solo / Iva Zanicchi – Zingara", "2. Sergio Endrigo / Mary Hopkin – Lontano dagli occhi", "3. Don Backy / Milva – Un sorriso", "4. Fausto Leali / Tony Del Monaco – Un’ora fa", "5. Nada / The Rokes – Ma che freddo fa", "6. Gigliola Cinquetti / France Gall – La pioggia", "7. The Showmen / Mal – Tu sei bella come sei", "8. Caterina Caselli / Johnny Dorelli – Il gioco dell’amore", "9. Lucio Battisti / Wilson Pickett – Un’avventura", "10. Orietta Berti / Massimo Ranieri – Quando l’amore diventa poesia", "11. Carmen Villani / Alessandra Casaccia – Piccola piccola", "12. Little Tony / Mario Zelinotti – Bada bambina", "13. Rita Pavone / Dik Dik – Zucchero", "14. Riccardo Del Turco / Antoine – Cosa hai messo nel caﬀé", "- Junior Magli / Casuals – Alla ﬁne della strada", "- Wilma Goich / Sweet Inspirations – Baci baci baci", "- Checco / Elio Gandolﬁ – Il sole è tramontato", "- Rosanna Fratello / Brenton Wood – Il treno", "- I New Trolls / Leonardo – Io che ho te", "- Robertino / Rocky y Roberts – Le belle donne", "- Mino Reitano / Claudio Villa – Meglio una sera (piangere da solo)", "- Armando Savini / Sonia – Non c’è che lei", "- Gabriella Ferri / Stevie Wonder – Se tu ragazzo mio", "- Memo Remigi / Isabella Jannetti – Una famiglia"],
        "1970": ["1. Adriano Celentano / Claudia Mori – Chi non lavora non fa l'amore", "2. Nicola Di Bari / Ricchi e Poveri – La prima cosa bella", "3. Sergio Endrigo / Iva Zanicchi – L'arca di Noè", "4. Ornella Vanoni / Camaleonti – Eternità", "5. Little Tony / Patty Pravo – La spada nel cuore", "6. Bobby Solo / Gigliola Cinquetti – Romantico blues", "7. Nada / Rosalino Cellamare – Pa' diglielo a ma'", "8. Anna Identici / Antoine – Taxi", "9. Luciano Tajoli / Mal – Sole, pioggia e vento", "10. Mario Tessuto / Orietta Berti – Tipitipitì", "11. Gianni Nazzaro / Marisa Sannia – L'amore è una colomba", "12. Carmen Villani / Fausto Leali – Hippy", "13. Sergio Leonardi / Tony Renis – Canzone blu", "14. Caterina Caselli / Nino Ferrer – Re di cuori", "- Rocky Roberts / Supergruppo – Accidenti", "- Lucia Rizzi / Michele – L'addio", "- Rita Pavone / Valeria Mongardini – Ahi, ahi, ragazzo", "- Ragazzi della via Gluck / Paolo Mengoli – Ahi! Che male che mi fai", "- Pino Donaggio / Sandie Shaw – Che eﬀetto mi fa", "- Rosanna Fratello / I Domodossola – Ciao anni verdi", "- Donatello / Dik Dik – Io mi fermo qui", "- Renato Rascel / Pio – Nevicava a Roma", "- Rossano / Dori Ghezzi – Occhi a mandorla", "- Francesco Banti / Dino Drusiani – Ora vivo", "- Claudio Villa / Tony Del Monaco – Serenata", "- Emiliana / Gens – La stagione di un ﬁore"],
        "1971": ["1. Nada / Nicola Di Bari – Il cuore è uno zingaro", "2. Ricchi e Poveri / José Feliciano – Che sarà", "3. Lucio Dalla / l'Equipe 84 – 4 marzo 1943", "4. Donatello / Marisa Sannia – Com'è dolce la sera", "5. Adriano Celentano / Coro Alpino Milanese – Sotto le lenzuola", "6. Domenico Modugno / Carmen Villani – Come stai?", "7. Don Backy / Gianni Nazzaro – Bianchi cristalli sereni", "8. Al Bano / Aguaviva – 13, storia d'oggi", "9. Gigliola Cinquetti / Ray Conniﬀ – Rose nel buio", "10. Caterina Caselli / Dik Dik – Ninna nanna (Cuore mio)", "11. Pino Donaggio / Peppino Di Capri – L'ultimo romantico", "12. Little Tony / Formula 3 – La folle corsa", "13. Sergio Endrigo / New Trolls – Una storia", "14. Sergio Menegale / Wallace Collection – Il sorriso il paradiso", "- Rosanna Fratello / Nino Ferrer – Amsterdam", "- Maurizio & Fabrizio / Protagonisti – Andata e ritorno", "- Paolo Mengoli / Mark e Martha – I ragazzi come noi", "- Antoine / Anna Identici – Il dirigibile", "- I Giganti / Fabio Trioli – Il viso di lei", "- Jordan / i Middle of the Road e Gens – Lo schiaﬀo", "- Edda Ollari / Lorenza Visconti – L'ora giusta", "- Nomadi / Mal – Non dimenticarti di me", "- Pio / Mau Cristiani – Occhi bianchi e neri", "- Piero Focaccia / Mungo Jerry – Santo Antonio Santo Francisco"],
        "1972": ["1. Nicola Di Bari – I giorni dell'arcobaleno", "2. Peppino Gagliardi – Come le viole", "3. Nada – Il re di denari", "4. Gianni Morandi – Vado a lavorare", "5. Gianni Nazzaro – Non voglio innamorarmi mai", "6. Delirium – Jesahel", "7. Marcella Bella – Montagne verdi", "8. Lucio Dalla – Piazza Grande", "9. Gigliola Cinquetti – Gira l'amore", "10. Donatello – Ti voglio", "11. Ricchi e Poveri – Un diadema di ciliegie", "12. Milva – Mediterraneo", "13. Lara Saint Paul – Se non fosse fra queste mie braccia lo inventerei", "14. Domenico Modugno – Un calcio alla città", "- Rita Pavone – Amici mai", "- Pino Donaggio – Ci sono giorni", "- Aguaviva – Ciao amico ciao", "- Anna Identici – Era bello il mio ragazzo", "- Marisa Sacchetto – La foresta selvaggia", "- Michele – Forestiero", "- Roberto Carlos – Un gatto nel blu", "- Carla Bissi – Il mio cuore se ne va", "- Delia – Per amore ricomincerei", "- Angelica – Portami via", "- Tony Cucchiara – Preghiera", "- Bobby Solo – Rimpianto", "- Fausto Leali – L'uomo e il cane", "- I Nuovi Angeli – Un viaggio in Inghilterra"],
        "1973": ["1. Peppino Di Capri – Un grande amore e niente più", "2. Peppino Gagliardi – Come un ragazzino", "3. Milva – Da troppo tempo", "4. Ricchi e Poveri – Dolce frutto", "5. Gilda Giuliani – Serena", "6. Wess y Dori Ghezzi – Tu nella mia vita", "7. Roberto Vecchioni – L'uomo che si gioca il cielo a dadi", "8. Fausto Leali – La bandiera di sole", "9. Umberto Balsamo – Amore mio", "10. Anna Identici – Mi son chiesta tante volte", "11. Camaleonti – Come sei bella", "12. Donatello – Tu giovane amore mio", "13. Memo Remigi – Il mondo è qui", "14. Alessandro – Tre minuti di ricordi", "15. Lionello – Straniera straniera", "16. Lara Saint Paul – Una casa grande", "- Mocedades – Addio amor", "- Pop Tops – Angeline", "- Jet – Anika na-o", "- Bassano – Cara amica", "- Carmen Amato – Dove andrai", "- Sergio Endrigo – Elisa Elisa", "- Lolita – Innamorata io?", "- Gigliola Cinquetti – Mistero", "- Christian De Sica – Mondo mio", "- Alberto Feri – Ogni volta che mi pare", "- Junior Magli – Povero", "- Le Figlie del Vento – Sugli sugli bane bane", "- Drupi – Vado via", "- Toni Santagata – Via Garibaldi"],
        "1974": ["1. Iva Zanicchi – Ciao, cara come stai?", "2. Domenico Modugno – Questa è la mia vita", "3. Orietta Berti – Occhi rossi", "- Anna Melato – Sta piovendo dolcemente", "- Emanuela Cortesi – Il mio volo bianco", "- Gilda Giuliani – Senza titolo", "- I Domodossola – Se hai paura", "- Les Charlots – Mon ami tango", "- Valentina Greco – Notte dell’estate", "- Nicola Di Bari – Il matto del villaggio", "- Mouth & MacNeal – Ah! L’amore", "- Gianni Nazzaro – A modo mio", "- Al Bano – In controluce", "- Mino Reitano – Innamorati", "- Rosanna Fratello – Un po’ di coraggio", "- Little Tony – Cavalli bianchi", "- Milva – Monica delle bambole", "- Middle of the Road – Sole giallo", "- Kambiz – Canta con me", "- Donatella Rettore – Capelli sciolti", "- Riccardo Fogli – Complici", "- Franco Simone – Fiume grande", "- Orchestra Spettacolo Casadei – La canta", "- Paola Musiani – La donna quando pensa", "- Antonella Bottazzi – Per una donna donna", "- Rossella – Qui", "- Sonia Gigliola Conti – Ricomincerei", "- Piero Focaccia – Valentin tango"],
        "1975": ["1. Gilda – Ragazza del sud", "2. Angela Luce – Ipocrisia", "3. Rosanna Fratello – Va' speranza va'", "4. Valentina Greco – Un grande addio", "5. Laura – E poi e poi", "6. Franco e le Piccole Donne – Come Humphrey Bogart", "- Le Nuove Erbe – Topolino piccolo", "- Nico dei Gabbiani – Io credo (ci son cose più grandi di te)", "- Eugenio Alberti – Decidi tu per me", "- Gianni Migliardi – Sei stata tu", "- Piero Cotto – Il telegramma", "- Stefania – L'incertezza di una vita", "- Emy Cesaroni – 1975... amore mio", "- Gabriella Sanna – Adesso basti tu", "- Daniela – Dolce abitudine", "- Eva 2000 – In amore non si può mentire", "- Jean-François Michael – Innamorarsi", "- Annagloria – La paura di morire", "- Antonella Bellan – Lettera", "- Lorenzo Pilat – Madonna d'amore", "- G.Men – Oggi", "- Kriss and Saratoga – Piccola bambina cara", "- La Quinta Faccia – Quattro stagioni", "- Paola Folzini – Il ragioniere", "- Goﬀredo Canarini – Scarafaggi", "- Paola Musiani – Se nasco un'altra volta", "- Le Volpi Blu – Senza impegno", "- Leila Selli – Sola in due", "- Nannarella – Sotto le stelle", "- Ely Neri and his Orchestra – Tango di casa mia"],
        "1976": ["1. Peppino Di Capri – Non lo faccio più", "2. Wess & Dori Ghezzi – Come stai, con chi sei", "3. Sandro Giacobbe – Gli occhi di tua madre", "4. Albatros – Volo AZ 504", "5. Paolo Frescura – Due anelli", "6. Drupi – Sambariò", "7. Carlo Gigli – Più forte", "8. Daniel Sentacruz Ensemble – Linda bella Linda", "9. Gli Opera – L'ho persa ancora", "10. Camaleonti – Cuore di vetro", "11. Orietta Berti – Omar", "12. La Strana Società – Andiamo via", "13. Ricchi e Poveri con I Nostri Figli – Due storie dei musicanti", "14. Patrizio Sandrelli – Piccola donna addio", "15. Sergio Endrigo – Quando c'era il mare", "16. Miko – Signora tu", "17. Profeti – Cercati un'anima", "18. La Nuova Gente – Che sarei", "- Santino Rocchetti – E tu mi manchi", "- Rosanna Fratello – Il mio primo rossetto", "- Gloriana – La canzone dei poveri", "- Antonio Buonomo – La femminista", "- Leano Morelli – Nata libera", "- Romina Power – Non due", "- Maggie Mae – Sing My Song", "- Armonium – Stella cadente", "- Vanna Leali – Torno a casa", "- Umberto Lupi – Una casa senza nome", "- Ezio Maria Picciotta – Uomo qualunque", "- Silvano Vittorio – Vieni"],
        "1977": ["1. Homo Sapiens – Bella da morire", "2. Collage – Tu mi rubi l'anima", "3. I Santo California – Monica", "- Umberto Napolitano – Con te ci sto", "- Santino Rocchetti – Dedicato a te", "- Daniela Davoli – E invece con te", "- Albatros – Gran Premio", "- Leano Morelli – Io ti porterei", "- Matia Bazar – Ma perché", "- Il Giardino dei Semplici – Miele", "- Donatella Rettore - Carmela", "- La Strana Società - Tesoro mio"],
        "1978": ["1. Matia Bazar – ...e dirsi ciao", "2. Anna Oxa – Un'emozione da poco", "3. Rino Gaetano – Gianna", "4. Ciro Sebastianelli – Il buio e tu", "5. Anselmo Genovese – Tu sola", "6. Santino Rocchetti – Armonia e poesia", "7. Schola Cantorum – Il mio amore", "8. Laura Luca – Domani domani", "9. Daniel Sentacruz Ensemble – 1/2 notte", "- Donato Ciletti – Anna Anna", "- Roberto Carrino – N ‘addore ‘e castagne", "- Dora Moroni – Ora", "- Marco Ferradini – Quando Teresa verrà", "- Beans – Soli"],
        "1979": ["1. Mino Vergnaghi – Amare", "2. Enzo Carella – Barbara", "3. I Camaleonti – Quell'attimo in più", "4. Collage – La gente parla", "5. Enrico Beruschi – Sarà un ﬁore", "6. Franco Fanigliulo – A me mi piace vivere alla grande", "7. Lorella Pescerelli – New York", "8. Kim & The Cadillacs – C’era un’atmosfera", "9. Umberto Napolitano – Bimba mia", "10. Pandemonium – Tu fai schifo sempre", "11. Antoine – Nocciolino", "12. Grimm – Liana", "- Marinella – Autunno cadono le pagine gialle", "- Ayx – Ayx Disco", "- Ciro Sebastianelli – Ciao Barbarella", "- Nicoletta Bauce – Grande Mago", "- Gli Opera – Il diario dei segreti", "- Il Était une Fois – Impazzirò", "- Michele Vicino – In due", "- Roberta – Il sole, la pioggia", "- Massimo Abbate – Napule cagnarrà", "- Gianni Mocchetti – Talismano nero"],
        "1980": ["1. Toto Cutugno – Solo noi", "2. Enzo Malepasso – Ti voglio bene", "3. Pupo – Su di noi", "- Gianni Morandi – Mariù", "- La Bottega dell'Arte – Più di una canzone", "- Sally Oldﬁeld – I Sing for You", "- Stefano Rosso – L'italiano", "- Leroy Gomez – Tu mi manchi dentro", "- Paolo Riviera – Cavallo bianco", "- Bobby Solo – Gelosia", "- Decibel – Contessa", "- Francesco Magni – Voglio l'erba voglio", "- Aldo Donati – Canterò canterò canterò", "- Giorgio Zito e i Diesel – Ma vai, vai!", "- Linda Lee – Va' pensiero", "- Bruno D'Andrea – Mara", "- Leano Morelli – Musica regina", "- Orlando Johnson – Il sole canta", "- Alberto Cheli – Passerà", "- Peppino di Capri – Tu cioè...", "- Omelet – Amor mio… sono me!", "- Rimmel – Angelo di seta", "- Henry Freis – Dal metrò a New York", "- Mela Lo Cicero – Dammi le mani", "- Gianfranco De Angelis – E pensare che una volta… non era così", "- Albetro Beltrami – Non ti drogare", "- Latte e Miele – Ritagli di luce", "- Armonium – Ti desidero", "- Luca Cola – Tu che fai la moglie", "- Coscarella y Polimeno – Tu sei la mia musica"],
        "1981": ["1. Alice – Per Elisa", "2. Loretta Goggi – Maledetta primavera", "3. Dario Baldan Bembo – Tu cosa fai stasera?", "4. Luca Barbarossa – Roma spogliata", "5. Ricchi e Poveri – Sarà perché ti amo", "6. Paolo Barabani – Hop hop somarello", "7. Marinella – Ma chi te lo fa fare", "8. Michele Zarrillo – Su quel pianeta libero", "9. Marcella – Pensa per te", "10. Passengers – Midnight", "- Eduardo De Crescenzo – Ancora", "- Leano Morelli – Angela", "- Orietta Berti – La barca non va più", "- Sterling Saint-Jacques – Blue (Tutto è blu)", "- Fiorella Mannoia – Caﬀè nero bollente", "- Carmen & Thompson – Follow me (Se amore vuoi)", "- Stefano Tosi – Io mi", "- Bobby Solo – Non posso perderti", "- Gianni Bella – Questo amore non si tocca", "- Collage – I ragazzi che si amano", "- Enzo Malepasso - Amore mio", "- Sebastiano Occhino - Bianca stella", "- Jo Chiarello - Che brutto aﬀare", "- Gli Opera - Guerriero", "- Umberto Napolitano - Mille volte ti amo", "- Tom Hooker - Toccami", "- Domenico Mattia - Tulilemble", "- Franco Fasano - Un’isola alle Hawaii"],
        "1982": ["1. Riccardo Fogli – Storie di tutti i giorni", "2. Al Bano Carrisi e Romina Power – Felicità", "3. Drupi – Soli", "4. Giuseppe Cionfoli – Solo grazie", "5. Christian – Un’altra vita un altro amore", "6. Milk & Coﬀee - Quando incontri l’amore", "- Jimmy Fontana – Beguine", "- Lene Lovich – Blue hotel", "- Elisabetta Viviani – C’è", "- Mia Martini – E non ﬁnisce mica il cielo", "- Anna Oxa – Io no", "- Stefano Sani – Lisa", "- Le Orme – Marinai", "- Riccardo Del Turco – Non voglio ali", "- Plastic Bertrand – Ping pong", "- Viola Valentino – Romatici", "- Mal – Sei la mia donna", "- Mario Castelnuovo – Sette ﬁli di canapa", "- Roberto Soﬃci – Strano momento", "- Bobby Solo – Tu stai", "- Zucchero – Una notte che vola via", "- Vasco Rossi – Vado al massimo", "- Orietta Berti – America in", "- Rino Martinez – Biancaneve", "- Marina Lai – Centomila amori miei", "- Julie – Cuore bandito", "- Claudio Villa – Facciamo la pace", "- Piero Cassano – Non arrenderti mai", "- Michele Zarrillo – Una rosa blu", "- Fiordaliso – Una sporca poesia"],
        "1983": ["1. Tiziana Rivale – Sarà quel che sarà", "2. Donatella Milani – Volevo dirti", "3. Dori Ghezzi – Margherita non lo sa", "4. Matia Bazar – Vacanze romane", "5. Toto Cutugno – L'italiano", "6. Fiordaliso – Oramai", "7. Stefano Sani – Complimenti", "8. Gianni Morandi – La mia nemica amatissima", "9. Amii Stewart – Working Late Tonight", "10. Marco Armani – È la vita", "11. Giuseppe Cionfoli – Shalom", "12. Giorgia Fiorio – Avrò", "13. Flavia Fortunato – Casco blu", "14. Bertín Osborne – Eterna malattia", "15. Riccardo Azzurri – Amare te", "16. Sandro Giacobbe – Primavera", "17. Christian – Abbracciami amore mio", "18. Marco Ferradini – Una catastrofe bionda", "19. Richard Sanderson – Stiamo insieme", "20. Zucchero – Nuvola", "21. Gianni Nazzaro – Mi sono innamorato di mia moglie", "22. Barbara Boncompagni – Notte e giorno", "23. Passengers – Movie Star", "24. Viola Valentino – Arriva arriva", "25. Vasco Rossi – Vita spericolata", "26. Pupo – Cieli azzurri", "- Daniela Goggi – Dammi tanto amore", "- Pinot – Donna sola", "- Brunella Borciani – E la neve scende", "- Patrizia Danzi – Fammi volare", "- Gloriana – Il mio treno", "- Nino Buonocore – Nuovo amore", "- Sibilla – Oppio", "- Alessio Colombini – Scatole cinesi", "- Manuele Pepe – Solo con te", "- Amedeo Minghi – 1950"],
        "1984": ["1. Al Bano y Romina Power – Ci sarà", "2. Toto Cutugno – Serenata", "3. Christian – Cara", "4. Pupo – Un amore grande", "5. Fiordaliso – Non voglio mica la luna", "6. Mario Castelnuovo – Nina", "7. Anna Oxa – Non scendo", "8. Drupi – Regalami un sorriso", "9. Iva Zanicchi – Chi (Mi darà)", "10. Patty Pravo – Per una bambola", "11. Gruppo Italiano – Anni ruggenti", "12. Bobby Solo – Ancora ti vorrei", "13. Donatella Milani – Libera", "14. Fiorella Mannoia – Come si cambia", "15. Marisa Sannia – Amore amore", "16. Alberto Camerini – La bottega del caﬀè", "17. Riccardo Del Turco – Serena alienazione", "18. Garbo – Radioclima", "19. Enrico Ruggeri – Nuovo swing", "20. Stadio – Allo stadio"],
        "1985": ["1. Ricchi e Poveri – Se m'innamoro", "2. Luis Miguel – Noi, ragazzi di oggi", "3. Gigliola Cinquetti – Chiamalo amore", "4. Riccardo Fogli – Sulla buona strada", "5. Christian – Notte serena", "6. Eros Ramazzotti – Una storia importante", "7. Anna Oxa – A lei", "8. Fiordaliso – Il mio angelo", "9. Peppino di Capri – E mo' e mo'", "10. Matia Bazar – Souvenir", "11. Marco Armani – Tu dimmi un cuore ce l'hai", "12. Drupi – Fammi volare", "13. Franco Simone – Ritratto", "14. Eduardo De Crescenzo – Via con me", "15. Banco del Mutuo Soccorso – Grande Joe", "16. Dario Baldan Bembo – Da quando non ci sei", "17. Ivan Graziani – Franca ti amo", "18. Eugenio Finardi – Vorrei svegliarti", "19. Mimmo Locasciulli – Buona fortuna", "20. New Trolls – Faccia di cane", "21. Zucchero Fornaciari & Randy Jackson Band - Donne", "22. Garbo - Cose veloci"],
        "1986": ["1. Eros Ramazzotti – Adesso tu", "2. Renzo Arbore – Il clarinetto", "3. Marcella – Senza un briciolo di testa", "4. Toto Cutugno – Azzurra malinconia", "5. Anna Oxa – È tutto un attimo", "6. Orietta Berti – Futuro", "7. Nino D'Angelo – Vai", "8. Fred Bongusto – Cantare", "9. Loredana Bertè – Re", "10. Fiordaliso – Fatti miei", "11. Marco Armani – Uno sull'altro", "12. Sergio Endrigo – Canzone italiana", "13. Rettore – Amore stella", "14. Mango – Lei verrà", "15. Righeira – Innamoratissimo (Tu che fai battere forte il mio cuore)", "16. Scialpi – No East, No West", "17. Enrico Ruggeri – Rien ne va plus", "18. Luca Barbarossa – Via Margutta", "19. Flavia Fortunato – Verso il 2000", "20. Rossana Casale – Brividi", "21. Zucchero Fornaciari - Canzone triste", "22. Stadio - Canzoni alla radio"],
        "1987": ["1. Gianni Morandi, Enrico Ruggeri y Umberto Tozzi – Si può dare di più", "2. Toto Cutugno – Figli", "3. Al Bano y Romina Power – Nostalgia canaglia", "4. Fausto Leali – Io amo", "5. Peppino Di Capri – Il sognatore", "6. Marcella – Tanti auguri", "7. Ricchi e Poveri – Canzone d'amore", "8. Fiorella Mannoia – Quello che le donne non dicono", "9. Luca Barbarossa – Come dentro un ﬁlm", "10. Christian – Aria e musica", "11. Lena Biolcati – Vita mia", "12. Rossana Casale – Destino", "13. Flavia Fortunato – Canto per te", "14. Dori Ghezzi – E non si ﬁnisce mai", "15. Eduardo De Crescenzo – L'odore del mare", "16. Scialpi – Bella età", "17. Le Orme – Dimmi che cos'è", "18. Mango – Dal cuore in poi", "19. Tony Esposito – Sinuè", "20. Patty Pravo – Pigramente signora", "21. Sergio Caputo - Il Garibaldi innamorato", "22. Mario Castelnuovo - Madonna di Venere", "23. Nino Buonocore - Rosanna", "24. Nada - Bolero"],
        "1988": ["1. Massimo Ranieri – Perdere l'amore", "2. Toto Cutugno – Emozioni", "3. Luca Barbarossa – L'amore rubato", "4. Marcella Bella – Dopo la tempesta", "5. Fausto Leali – Mi manchi", "6. Mino Reitano – Italia", "7. Anna Oxa – Quando nasce un amore", "8. Fiordaliso & Claudio Cabrini – Per noi", "9. Ricchi e Poveri – Nascerà Gesù", "10. Fiorella Mannoia – Le notti di maggio", "11. Raf – Inevitabile follia", "12. Francesco Nuti – Sarà per te", "13. Franco Califano – Io (per le strade di quartiere)", "14. Figli di Bubba – Nella valle dei Timbales", "15. Michele Zarrillo – Come un giorno di sole", "16. Loredana Bertè – Io", "17. Peppino di Capri – Nun chiagnere", "18. Tullio De Piscopo – Andamento lento", "19. Matia Bazar – La prima stella della sera", "20. Drupi – Era bella davvero", "21. Ron – Il mondo avrà una grande anima", "22. Flavia Fortunato – Una bella canzone", "23. New Trolls – Cielo chiaro", "24. Denovo – Ma che idea", "25. Nino Buonocore – Le tue chiavi non ho", "26. Alan Sorrenti – Come per miracolo"],
        "1989": ["1. Anna Oxa y Fausto Leali – Ti lascerò", "2. Toto Cutugno – Le mamme", "3. Al Bano y Romina Power – Cara terra mia", "4. Riccardo Fogli – Non ﬁnisce così", "5. Jovanotti – Vasco", "6. Fiordaliso – Se non avessi te", "7. Francesco Salvi – Esatto", "8. Ricchi e Poveri – Chi voglio sei tu", "9. Mia Martini – Almeno tu nell'universo", "10. Ornella Vanoni – Io come farò", "11. Peppino di Capri – Il mio pianoforte", "12. Marisa Laurito – Il babà è una cosa seria", "13. Gino Paoli – Questa volta no", "14. Renato Carosone – ’Na canzuncella doce doce", "15. Raf – Cosa resterà degli anni ’80", "16. Dori Ghezzi – Il cuore delle donne", "17. Enzo Jannacci – Se me lo dicevi prima", "18. Gigliola Cinquetti – Ciao", "19. Rossana Casale – A che servono gli dei", "20. Tullio De Piscopo – E allora e allora", "21. Eduardo De Crescenzo – Come mi vuoi", "22. Fred Bongusto – Scusa", "23. Gigi Sabani – La ﬁne del mondo", "24. Sergio Caputo – Rifarsi una vita"],
        "1990": ["1. Pooh – Uomini soli", "2. Toto Cutugno – Gli amori", "3. Amedeo Minghi y Mietta – Vattene amore", "4. Anna Oxa – Donna con te", "5. Marcella y Gianni Bella – Verso l’ignoto", "6. Mia Martini – La nevicata del ’56", "7. Mango – Tu…sì", "8. Francesco Salvi – A", "9. Caterina Caselli – Bisognerebbe non pensare che a te", "10. Riccardo Fogli – Ma quale amore", "11. Sandro Giacobbe – Io vorrei", "12. Paola Turci – Ringrazio Dio", "13. Milva – Sono felice", "14. Grazia Di Michele – Io e mio padre", "15. Peppino Di Capri – Evviva Maria", "16. Eugenio Bennato y Tony Esposito – Novecento aufwiedersehen", "17. Ricchi e Poveri – Buona giornata", "18. Lena Biolcati – Amori", "19. Mino Reitano – Vorrei", "20. Christian – Amore"],
        "1991": ["1. Riccardo Cocciante – Se stiamo insieme", "2. Renato Zero – Spalle al muro", "3. Marco Masini – Perché lo fai", "4. Umberto Tozzi – Gli altri siamo noi", "5. Pierangelo Bertoli y Tazenda – Spunta la Luna dal monte", "6. Amedeo Minghi – Nené", "7. Mietta – Dubbi no", "8. Al Bano y Romina Power – Oggi sposi", "9. Riccardo Fogli – Io ti prego di ascoltare", "10. Raf – Oggi un Dio non ho", "11. Enzo Jannacci – La fotograﬁa", "12. Fiordaliso – Il mare più grande che c'è (I Love You Man)", "13. Jo Squillo y Sabrina Salerno – Siamo donne", "14. Ladri di Biciclette – Sbatti ben su del Be Bop", "15. Eduardo De Crescenzo – E la musica va", "16. Grazia Di Michele – Se io fossi un uomo", "17. Rossana Casale – Terra", "18. Loredana Bertè – In questa città", "19. Gianni Bella – La ﬁla degli oleandri", "20. Mariella Nava – Gli uomini"],
        "1992": ["1. Luca Barbarossa – Portami a ballare", "2. Mia Martini – Gli uomini non cambiano", "3. Paolo Vallesi – La forza della vita", "4. Pierangelo Bertoli – Italia d’oro", "5. Massimo Ranieri – Ti penso", "6. Matia Bazar – Piccoli giganti", "7. Flavia Fortunato y Franco Fasano – Per niente al mondo", "8. Tazenda – Pitzinnos in sa gherra", "9. Fausto Leali – Perchè", "10. Riccardo Fogli – In una notte così", "11. Michele Zarrillo – Strade di Roma", "12. Mariella Nava – Mendicante", "13. Drupi – Un uomo in più", "14. Peppino di Capri y Pietra Montecorvino – Favola blues", "15. New Trolls – Quelli come noi", "- Ricchi e Poveri – Così lontani", "- Scialpi – È una nanna", "- Lina Sastri – Femmene ‘e mare", "- Paolo Mengoli – Io ti darò", "- Enzo Ghinazzi – La mia preghiera", "- Mino Reitano – Ma ti sei chiesto mai", "- Nuova Compagnia di Canto Popolare – Pe’ dispietto", "- Giorgio Faletti y Orietta Berti – Rumba di tango", "- Formula 3 – Un frammento rosa"],
        "1993": ["1. Enrico Ruggeri – Mistero", "2. Cristiano De André – Dietro la porta", "3. Rossana Casale y Grazia Di Michele – Gli amori diversi", "4. Matia Bazar – Dedicato a te", "5. Renato Zero – Ave Maria", "6. Mietta y Ragazzi di Via Meda – Figli di chi", "7. Paola Turci – Stato di calma apparente", "8. Biagio Antonacci – Non so più a chi credere", "9. Amedeo Minghi – Notte bella, magniﬁca", "10. Francesca Alotta – Un anno di noi", "11. Andrea Mingardi – Sogno", "12. Roberto Murolo – L'Italia è bella", "13. Tullio De Piscopo – Qui gatta ci cova", "14. Loredana Bertè y Mia Martini – Stiamo come stiamo", "15. Nino Buonocore – Una canzone d'amore", "- Jo Squillo – Balla italiano", "- Ladri di Biciclette y Tony Esposito – Cambiamo musica", "- Maurizio Vandelli, Dik Dik y Camaleonti – Come passa il tempo", "- Francesco Salvi – Dammi 1 bacio", "- Peppino Gagliardi – L'alba", "- Peppino di Capri – La voce delle stelle", "- Schola Cantorum – Sulla strada del mare", "- Alessandro Canino – Tu tu tu tu", "- Milva – Uomini addosso"],
        "1994": ["1. Aleandro Baldi - Passerà", "2. Giorgio Faletti - Signor tenente", "3. Laura Pausini - Strani amori", "4. Gerardina Trovato - Non è un ﬁlm", "5. Michele Zarrillo - Cinque giorni", "6. Enzo Jannacci y Paolo Rossi - I soliti accordi", "7. Ivan Graziani - Maledette malelingue", "8. Andrea Mingardi - Amare amare", "9. Marco Armani - Esser duri", "10. Donatella Rettore - Di notte specialmente", "11. Mariella Nava - Terra mia", "12. Formula 3 - La casa dell'imperatore", "13. Loredana Bertè - Amici non ne ho", "14. Alessandro Canino - Crescerai", "15. Francesco Salvi - Statento", "16. Alessandro Bono - Oppure no", "17. Claudia Mori - Se mi ami...", "18. Carlo Marrale - L'ascensore", "19. Squadra Italia - Una vecchia canzone italiana", "20. Franco Califano - Napoli"],
        "1995": ["1. Giorgia - Come saprei", "2. Gianni Morandi y Barbara Cola - In amore", "3. Ivana Spagna - Gente come noi", "4. Andrea Bocelli - Con te partirò", "5. Fiorello - Finalmente tu", "6. Danilo Amerio - Bisogno d'amore", "7. Lighea - Rivoglio la mia vita", "8. 883 - Senza averti qui", "9. Antonella Arancio - Più di così", "10. Lorella Cuccarini - Un altro amore no", "11. Mango - Dove vai...", "12. Giorgio Faletti - L'assurdo mestiere", "13. Trio Melody - Ma che ne sai... (...se non hai fatto il piano-bar)", "14. Gigliola Cinquetti - Giovane vecchio cuore", "15. Massimo Ranieri - La vestaglia", "16. Drupi - Voglio una donna", "17. Toto Cutugno - Voglio andare a vivere in campagna", "18. Sabina Guzzanti y La Riserva Indiana - Troppo sole", "19. Loredana Bertè - ANGELI & angeli", "20. Patty Pravo - I giorni dell'armonia", "- Francesca Schiavo - Amore e guerra", "- Valeria Visconti - È con te", "- Giò Di Tonno - Padre e padrone"],
        "1996": ["1. Ron y Tosca - Vorrei incontrarti fra cent'anni", "2. Elio e le Storie Tese - La terra dei cachi", "3. Giorgia - Strano il mio destino", "4. Ivana Spagna - E io penso a te", "5. Neri per Caso - Mai più sola", "6. Massimo Di Cataldo - Se adesso te ne vai", "7. Al Bano - È la mia vita", "8. Aleandro Baldi y Marco Guerzoni - Soli al bar", "9. Amedeo Minghi - Cantare è d'amore", "10. Paola Turci - Volo così", "11. Michele Zarrillo - L'elefante e la farfalla", "12. Luca Barbarossa - Il ragazzo con la chitarra", "13. Federico Salvatore - Sulla porta", "14. Rossella Marcone - Una vita migliore", "15. Enrico Ruggeri - L'amore è un attimo", "16. Raﬀaella Cavalli - Sarò", "17. Gigi Finizio - Solo lei", "18. Paolo Vallesi - Non andare via", "19. Riccardo Fogli - Romanzo", "20. Umberto Bindi y New Trolls - Letti", "- Dhamm - Ama", "- Mara - Non è amore", "- Fedele Boccassini - Non scherzare dai"],
        "1997": ["1. Jalisse - Fiumi di parole", "2. Anna Oxa - Storie", "3. Syria - Sei tu", "4. Silvia Salemi - A casa di Luca", "5. Fausto Leali - Non ami che te", "6. O.R.O. - Padre Nostro", "7. Nek - Laura non c'è", "8. Patty Pravo - ...e dimmi che non vuoi morire", "9. Massimo Ranieri - Ti parlerò d'amore", "10. Tosca - Nel respiro più grande", "11. Francesco Baccini - Senza tù", "12. Dirotta su Cuba - È andata così", "13. Marina Rei - Dentro me", "14. Al Bano - Verso il sole", "15. Cattivi Pensieri - Quello che sento", "16. Pitura Freska - Papa nero", "17. Toto Cutugno - Faccia pulita", "18. Ragazzi Italiani - Vero amore", "19. New Trolls y Greta - Alianti liberi", "20. Loredana Bertè - Luna", "- Alessandro Mara - Attimi", "- Camilla - Come ti tradirei", "- Carmen Consoli - Confusa e felice", "- Alessandro Errico - E penserò al tuo viso…", "- Leandro Barsotti - Fragolina", "- Maurizio Lauzi - Il capo dei giocattoli", "- Olivia - Quando viene sera", "- Adriana Ruocco - Uguali uguali", "- Petra Magoni - Voglio un dio"],
        "1998": ["1. Annalisa Minetti – Senza te o con te", "2. Antonella Ruggiero – Amore lontanissimo", "3. Lisa – Sempre", "4. Paola Turci – Solo come me", "5. Silvia Salemi – Pathos", "6. Mango y Zenîma – Luce", "7. Luca Sepe – Un po' di te", "8. Niccolò Fabi – Lasciarsi un giorno a Roma", "9. Ron – Un porto nel vento", "10. Andrea Mingardi – Canto per te", "11. Alex Baroni – Sei tu o lei (Quello che voglio)", "12. Ivana Spagna – E che mai sarà", "13. Piccola Orchestra Avion Travel – Dormi e sogna", "14. Sergio Caputo – Flamingo", "15. Nuova Compagnia di Canto Popolare – Sotto il velo del cielo", "16. Paola e Chiara – Per te", "17. Enzo Jannacci – Quando un musicista ride"],
        "1999": ["1. Anna Oxa – Senza pietà", "2. Antonella Ruggiero – Non ti dimentico (Se non ci fossero le nuvole)", "3. Mariella Nava – Così è la vita", "4. Enzo Gragnaniello y Ornella Vanoni – Alberi", "5. Stadio – Lo zaino", "6. Al Bano – Ancora in volo", "7. Marina Rei – Un inverno da baciare", "8. Nino D'Angelo – Senza giacca e cravatta", "9. Daniele Silvestri – Aria", "10. Nada – Guardami negli occhi", "11. Eugenio Finardi – Amami Lara", "12. Gatto Panceri – Dove dov'è", "13. Gianluca Grignani – Il giorno perfetto", "14. Massimo Di Cataldo – Come sei bella"],
        "2000": ["1. Piccola Orchestra Avion Travel - Sentimento", "2. Irene Grandi - La tua ragazza sempre", "3. Gianni Morandi - Innamorato", "4. Max Gazzè - Il timido ubriaco", "5. Samuele Bersani - Replay", "6. Gerardina Trovato - Gechi e vampiri", "7. Carmen Consoli - In bianco e nero", "8. Matia Bazar - Brivido caldo", "9. Alice - Il giorno dell'indipendenza", "10. Gigi D'Alessio - Non dirgli mai", "11. Subsonica - Tutti i miei sbagli", "12. Ivana Spagna - Con il tuo nome", "13. Mietta - Fare l'amore", "14. Mariella Nava y Amedeo Minghi - Futuro come te", "15. Marco Masini - Raccontami di te", "16. Umberto Tozzi - Un'altra vita"],
        "2001": ["1. Elisa - Luce (tramonti a nord est)", "2. Giorgia - Di sole e d'azzurro", "3. Matia Bazar - Questa nostra grande storia d'amore", "4. Michele Zarrillo - L'acrobata", "5. Paola Turci - Saluto l'inverno", "6. Jenny B - Anche tu", "7. Alex Britti - Sono contento", "8. Gigi D'Alessio - Tu che ne sai", "9. Fabio Concato - Ciao Ninìn", "10. Anna Oxa - L'eterno movimento", "11. Peppino di Capri - Pioverà (Habibi ené)", "12. Gianni Bella - Il profumo del mare", "13. Syria - Fantasticamenteamore", "14. Sottotono - Mezze verità", "15. Quintorigo - Bentivoglio Angelina (Kon tutto il mio amaro)", "16. Bluvertigo - L'assenzio (The Power of Nothing)"],
        "2002": ["1. Matia Bazar - Messaggio d'amore", "2. Alexia - Dimmi come…", "3. Gino Paoli - Un altro amore", "4. Fausto Leali y Luisa Corna - Ora che ho bisogno di te", "5. Enrico Ruggeri - Primavera a Sarajevo", "6. Mariella Nava - Il cuore mio", "7. Filippa Giordano - Amarti sì", "8. Francesco Renga - Tracce di te", "9. Fiordaliso - Accidenti a te", "10. Gazosa - Ogni giorno di più", "11. Michele Zarrillo - Gli angeli", "12. Gianluca Grignani - Lacrime dalla Luna", "13. Alessandro Saﬁna - Del perduto amore", "14. Daniele Silvestri - Salirò", "15. Nino D'Angelo - Marì", "16. Patty Pravo - L'immenso", "17. Loredana Bertè - Dimmi che mi ami", "18. Mino Reitano - La mia canzone", "19. Lollipop - Batte forte", "20. Timoria - Casa mia"],
        "2003": ["1. Alexia – Per dire di no", "2. Alex Britti – 7000 caﬀè", "3. Sergio Cammariere – Tutto quello che un uomo", "4. Enrico Ruggeri y Andrea Mirò – Nessuno tocchi Caino", "5. Syria – L'amore è", "6. Lisa – Oceano", "7. Giuni Russo – Morirò d'amore", "8. Silvia Salemi – Nel cuore delle donne", "9. Antonella Ruggiero – Di un amore", "10. Luca Barbarossa – Fortuna", "11. Nino D'Angelo – 'A storia 'e nisciuno", "12. Cristiano De André – Un giorno nuovo", "13. Fausto Leali – Eri tu", "14. Anna Oxa – Cambierò", "15. Eiﬀel 65 – Quelli che non hanno età", "16. Bobby Solo y Little Tony – Non si cresce mai", "17. Anna Tatangelo y Federico Stragà – Volere volare", "18. Negrita – Tonight", "19. Amedeo Minghi – Sarà una canzone", "20. Iva Zanicchi – Fossi un tango"],
        "2004": ["1. Marco Masini – L'uomo volante", "2. Mario Rosini – Sei la vita mia", "3. Linda – Aria, sole, terra e mare", "4. Paolo Meneguzzi – Guardami negli occhi (prego)", "5. Bungaro – Guardastelle", "6. Massimo Modugno y Gipsy Kings – Quando l'aria mi sﬁora", "7. Stefano Picchi – Generale Kamikaze", "8. Morris Albert y Mietta – Cuore", "9. Neﬀa – Le ore piccole", "10. Mario Venuti – Crudele", "11. DJ Francesco – Era bellissimo", "12. Simone Tomassini – È stato tanto tempo fa", "13. DB Boulevard y Bill Wyman – Basterà", "14. Andrea Mingardi y The Blues Brothers Band – È la musica", "15. Omar Pedrini – Lavoro inutile", "16. Daniele Groﬀ – Sei un miracolo", "17. Adriano Pappalardo – Nessun consiglio", "18. Veruska – Un angelo legato a un palo", "19. Andrè – Il nostro amore", "20. Danny Losito y Las Ketchup – Single", "21. Paciﬁco – Solo un sogno", "22. Piotta – Ladro di te"],
        "2005": ["1. Francesco Renga – Angelo", "2. Toto Cutugno y Annalisa Minetti – Come noi nessuno al mondo", "3. Antonella Ruggiero – Echi d'inﬁnito", "4. Nicky Nicolai y Stefano Di Battista Jazz Quartet – Che mistero è l'amore", "5. Laura Bono – Non credo nei miracoli", "6. Marcella Bella – Uomo bastardo", "7. Anna Tatangelo – Ragazza di periferia", "8. Alexia – Da grande", "9. Matia Bazar – Grido d'amore", "10. Gigi D'Alessio – L'amore che non c'è", "11. Veronica Ventavoli – L'immaginario", "12. Peppino di Capri – La panchina", "13. Marco Masini – Nel mondo dei sogni", "14. Le Vibrazioni – Ovunque andrò", "15. La Diﬀerenza – Che farò", "- DJ Francesco Band – Francesca", "- Paolo Meneguzzi – Non capiva che l'amavo", "- Marina Rei – Fammi entrare", "- Nicola Arigliano – Colpevole", "- Giovanna D'Angi – Fammi respirare", "- Max De Angelis – Sono qui per questo", "- Equ – L'idea", "- Franco Califano – Non escludo il ritorno", "- Velvet – Dovevo dirti molte cose", "- Christian Lo Zito – Segui il tuo cuore", "- Sabrina Guida – Vorrei", "- Modà - Riesci a innamorarmi", "- Paola e Chiara – A modo mio", "- Umberto Tozzi – Le parole", "- Concido – Ci vuole k…", "- Enrico Boccadoro – Dov'è la terra capitano", "- Negramaro – Mentre tutto scorre"],
        "2006": ["1. Povia – Vorrei avere il becco", "2. Nomadi – Dove si va", "3. Anna Tatangelo – Essere una donna", "4. Riccardo Maﬀoni – Sole negli occhi", "- Simone Cristicchi – Che bella gente", "- Dolcenera – Com'è straordinaria la vita", "- Michele Zarrillo – L'alfabeto degli amanti", "- Zero Assoluto – Svegliarsi la mattina", "- Simona Bencini – Tempesta", "- Nicky Nicolai – Lei ha la notte", "- Ron – L'uomo delle stelle", "- Alex Britti – Solo con te", "- I Ragazzi di Scampia con Gigi Finizio – Musica e speranza", "- Sugarfree – Solo lei mi dà", "- Monia Russo – Un mondo senza parole", "- L'Aura – Irraggiungibile", "- Helena Hellwig – Di luna morirei", "- Tiziano Orecchio – Preda innocente", "- Noa, Carlo Fava & Solis String Quartet – Un discorso in generale", "- Ivana Spagna – Noi non possiamo cambiare", "- Luca Dirisio – Sparirò", "- Andrea Ori – Nel tuo mare", "- Ameba 4 – Rido... forse mi sbaglio", "- Ivan Segreto – Con un gesto", "- Anna Oxa – Processo a me stessa", "- Mario Venuti y Arancia Sonora – Un altro posto nel mondo", "- Gianluca Grignani – Liberi di sognare", "- Antonello – Capirò crescerai", "- Deasonika – Non dimentico più…", "- Virginio – Davvero"],
        "2007": ["1. Simone Cristicchi – Ti regalerò una rosa", "2. Al Bano – Nel perdono", "3. Piero Mazzocchetti – Schiavo d'amore", "4. Daniele Silvestri – La paranza", "5. Mango – Chissà se nevica", "6. Paolo Meneguzzi – Musica", "7. Tosca – Il terzo fuochista", "8. Francesco y Roby Facchinetti – Vivere normale", "9. Zero Assoluto – Appena prima di partire", "10. Antonella Ruggiero – Canzone fra le guerre", "11. Amalia Gré – Amami per sempre", "12. Marcella y Gianni Bella – Forever per sempre", "13. Stadio – Guardami", "14. Paolo Rossi – In Italia si sta male (si sta bene anziché no)", "15. Nada – Luna in piena", "16. Johnny Dorelli – Meglio così", "17. Fabio Concato – Oltre il giardino", "18. Leda Battisti – Senza me ti pentirai", "19. Milva – The Show Must Go On", "20. Velvet – Tutto da rifare"],
        "2008": ["1. Giò Di Tonno y Lola Ponce – Colpo di fulmine", "2. Anna Tatangelo – Il mio amico", "3. Fabrizio Moro – Eppure mi hai cambiato la vita", "4. Toto Cutugno – Un falco chiuso in gabbia", "5. Finley – Ricordi", "6. Paolo Meneguzzi – Grande", "7. Sergio Cammariere – L'amore non si spiega", "8. Gianluca Grignani – Cammina nel sole", "9. Little Tony – Non ﬁnisce qui", "10. Eugenio Bennato – Grande sud", "11. Mietta – Baciami adesso", "12. Max Gazzè – Il solito sesso", "13. L'Aura – Basta!", "14. Frankie hi-nrg mc – Rivoluzione", "15. Michele Zarrillo – L'ultimo ﬁlm insieme", "16. Tricarico – Vita tranquilla", "17. Tiromancino – Il rubacuori", "18. Amedeo Minghi – Cammina cammina", "19. Mario Venuti – A ferro e fuoco", "- Loredana Bertè – Musica e parole (descaliﬁcada)"],
        "2009": ["1. Marco Carta - La forza mia", "2. Povia - Luca era gay", "3. Sal Da Vinci - Non riesco a farti innamorare", "- Francesco Renga - Uomo senza età", "- Fausto Leali - Una piccola parte di te", "- Marco Masini - L'Italia", "- Patty Pravo - E io verrò un giorno là", "- Alexia y Mario Lavezzi - Biancaneve", "- Al Bano - L'amore è sempre amore", "- Pupo, Paolo Belli y Youssou N'Dour - L'opportunità", "- Dolcenera - Il mio amore unico", "- Gemelli Diversi - Vivi per un miracolo", "- Nicky Nicolai y Stefano Di Battista - Più sole", "- Afterhours - Il paese è reale", "- Tricarico - Il bosco delle fragole", "- Iva Zanicchi - Ti voglio senza amore"],
        "2010": ["1. Valerio Scanu - Per tutte le volte che...", "2. Pupo y Emanuele Filiberto con Luca Canonici - Italia amore mio", "3. Marco Mengoni - Credimi ancora", "4. Noemi - Per tutta la vita", "5. Malika Ayane - Ricomincio da qui", "6. Irene Fornaciari y Nomadi - Il mondo piange", "7. Simone Cristicchi - Meno male", "8. Irene Grandi - La cometa di Halley", "9. Arisa - Malamorenò", "10. Povia - La verità", "- Enrico Ruggeri - La notte delle fate", "- Fabrizio Moro - Non è una canzone", "- Sonohra - Baby", "- Nino D'Angelo con Maria Nazionale - Jammo jà", "- Toto Cutugno - Aeroplani"],
        "2011": ["1. Roberto Vecchioni - Chiamami ancora amore", "2. Modà y Emma - Arriverà", "3. Al Bano - Amanda è libera", "4. Davide Van De Sfroos - Yanez", "5. Luca Madonia y Franco Battiato - L'alieno", "6. La Crus - Io confesso", "7. Nathalie - Vivo sospesa", "8. Luca Barbarossa y Raquel del Rosario - Fino in fondo", "9. Anna Tatangelo - Bastardo", "10. Giusy Ferreri - Il mare immenso", "- Max Pezzali - Il mio secondo tempo", "- Tricarico - Tre colori", "- Patty Pravo - Il vento e le rose", "- Anna Oxa - La mia anima d'uomo"],
        "2012": ["1. Emma - Non è l'inferno", "2. Arisa - La notte", "3. Noemi - Sono solo parole", "4. Gigi D'Alessio y Loredana Bertè - Respirare", "5. Pierdavide Carone y Lucio Dalla - Nanì", "6. Dolcenera - Ci vediamo a casa", "7. Nina Zilli - Per sempre", "8. Francesco Renga - La tua bellezza", "9. Samuele Bersani - Un pallone", "10. Eugenio Finardi - E tu lo chiami Dio", "- Matia Bazar - Sei tu", "- Chiara Civello - Al posto del mondo", "- Irene Fornaciari - Grande mistero", "- Marlene Kuntz - Canzone per un ﬁglio"],
        "2013": ["1. Marco Mengoni - L'essenziale", "2. Elio e le Storie Tese - La canzone mononota", "3. Modà - Se si potesse non morire", "4. Malika Ayane - E se poi", "5. Raphael Gualazzi - Sai (ci basta un sogno)", "6. Daniele Silvestri - A bocca chiusa", "7. Max Gazzè - Sotto casa", "8. Chiara - Il futuro che sarà", "9. Annalisa - Scintille", "10. Maria Nazionale - È colpa mia", "11. Simone Cristicchi - La prima volta (che sono morto)", "12. Marta sui Tubi - Vorrei", "13. Simona Molinari y Peter Cincotti - La felicità", "14. Almamegretta - Mamma non lo sa", "- Marco Mengoni - Bellissimo", "- Modà - Come l'acqua dentro il mare", "- Elio e le Storie Tese - Dannati forever", "- Marta sui Tubi - Dispari", "- Simona Molinari y Peter Cincotti - Dr. Jekyll Mr. Hyde", "- Max Gazzè - I tuoi maledettissimi impegni", "- Daniele Silvestri - Il bisogno di te (ricatto d'onor)", "- Chiara - L'esperienza dell'amore", "- Simone Cristicchi - Mi manchi", "- Malika Ayane - Niente", "- Annalisa - Non so ballare", "- Almamegretta - Onda che vai", "- Maria Nazionale - Quando non parlo", "- Raphael Gualazzi - Senza ritegno"],
        "2014": ["1. Arisa - Controvento", "2. Raphael Gualazzi & The Bloody Beetroots - Liberi o no", "3. Renzo Rubino - Ora", "4. Francesco Renga - Vivendo adesso", "5. Noemi - Bagnati dal sole", "6. Perturbazione - L'unica", "7. Cristiano De André - Il cielo è vuoto", "8. Frankie hi-nrg mc - Pedala", "9. Giusy Ferreri - Ti porto a cena con me", "10. Francesco Sarcina - Nel tuo sorriso", "11. Giuliano Palma - Così lontano", "12. Antonella Ruggiero - Da lontano", "13. Ron - Sing in the rain", "- Francesco Renga - A un isolato da te", "- Francesco Sarcina - In questa città", "- Cristiano De André - Invisibili", "- Giusy Ferreri - L'amore possiede il bene", "- Perturbazione - L'Italia vista dal bar", "- Arisa - Lentamente (Il primo che passa)", "- Renzo Rubino - Per sempre e poi basta", "- Antonella Ruggiero - Quando balliamo", "- Raphael Gualazzi & The Bloody Beetroots - Tanto ci sei", "- Giuliano Palma - Un bacio crudele", "- Noemi - Un uomo è un albero", "- Frankie hi-nrg mc - Un uomo è vivo", "- Ron - Un abbraccio unico", "- Riccardo Sinigallia - Una rigenerazione", "- Riccardo Sinigallia - Prima di andare via (descaliﬁcado)"],
        "2015": ["1. Il Volo - Grande amore", "2. Nek - Fatti avanti amore", "3. Malika Ayane - Adesso e qui (nostalgico presente)", "4. Annalisa - Una ﬁnestra tra le stelle", "5. Chiara - Straordinario", "6. Marco Masini - Che giorno è", "7. Dear Jack - Il mondo esplode tranne noi", "8. Gianluca Grignani - Sogni infranti", "9. Nina Zilli - Sola", "10. Lorenzo Fragola - Siamo uguali", "11. Alex Britti - Un attimo importante", "12. Irene Grandi - Un vento senza nome", "13. Nesli - Buona fortuna amore", "14. Bianca Atzei - Il solo al mondo", "15. Moreno - Oggi ti parlo così", "16. Grazia Di Michele y Mauro Coruzzi - Io sono una ﬁnestra", "- Raf - Come una favola", "- Biggio y Mandelli - Vita d'inferno", "- Anna Tatangelo - Libera", "- Lara Fabian - Voce"],
        "2016": ["1. Stadio - Un giorno mi dirai", "2. Francesca Michielin - Nessun grado di separazione", "3. Giovanni Caccamo y Deborah Iurato - Via da qui", "4. Enrico Ruggeri - Il primo amore non si scorda mai", "5. Lorenzo Fragola - Inﬁnite volte", "6. Patty Pravo - Cieli immensi", "7. Clementino - Quando sono lontano", "8. Noemi - La borsa di una donna", "9. Rocco Hunt - Wake Up", "10. Arisa - Guardando il cielo", "11. Annalisa - Il diluvio universale", "12. Elio e le Storie Tese - Vincere l'odio", "13. Valerio Scanu - Finalmente piove", "14. Alessio Bernabei - Noi siamo inﬁnito", "15. Dolcenera - Ora o mai più (le cose cambiano)", "16. Irene Fornaciari - Blu", "- Zero Assoluto - Di me e di te", "- Bluvertigo - Semplicemente", "- Neﬀa - Sogni e nostalgia", "- Dear Jack - Mezzo respiro"],
        "2017": ["1. Francesco Gabbani - Occidentali's Karma", "2. Fiorella Mannoia - Che sia benedetta", "3. Ermal Meta - Vietato morire", "4. Michele Bravi - Il diario degli errori", "5. Paola Turci - Fatti bella per te", "6. Sergio Sylvestre - Con te", "7. Fabrizio Moro - Portami via", "8. Elodie - Tutta colpa mia", "9. Bianca Atzei - Ora esisti solo tu", "10. Samuel - Vedrai", "11. Michele Zarrillo - Mani nelle mani", "12. Lodovica Comello - Il cielo non mi basta", "13. Marco Masini - Spostato di un secondo", "14. Chiara - Nessun posto è casa mia", "15. Alessio Bernabei - Nel mezzo di un applauso", "16. Clementino - Ragazzi fuori", "- Al Bano - Di rose e di spine", "- Gigi D'Alessio - La prima stella", "- Ron - L'ottava meraviglia", "- Giusy Ferreri - Fa talmente male", "- Raige y Giulia Luzi - Togliamoci la voglia", "- Nesli y Alice Paba - Do retta a te"],
        "2018": ["1. Ermal Meta y Fabrizio Moro - Non mi avete fatto niente", "2. Lo Stato Sociale - Una vita in vacanza", "3. Annalisa - Il mondo prima di te", "4. Ron - Almeno pensami", "5. Ornella Vanoni con Bungaro y Paciﬁco - Imparare ad amarsi", "6. Max Gazzè - La leggenda di Cristalda e Pizzomunno", "7. Luca Barbarossa - Passame er sale", "8. Diodato y Roy Paci - Adesso", "9. The Kolors - Frida (mai, mai, mai)", "10. Giovanni Caccamo - Eterno", "11. Le Vibrazioni - Così sbagliato", "12. Enzo Avitabile y Peppe Servillo - Il coraggio di ogni giorno", "13. Renzo Rubino - Custodire", "14. Noemi - Non smettere mai di cercarmi", "15. Red Canzian - Ognuno ha il suo racconto", "16. Decibel - Lettera dal Duca", "17. Nina Zilli - Senza appartenere", "18. Roby Facchinetti y Riccardo Fogli - Il segreto del tempo", "19. Mario Biondi - Rivederti", "20. Elio e le Storie Tese - Arrivedorci"],
        "2019": ["1. Mahmood - Soldi", "2. Ultimo - I tuoi particolari", "3. Il Volo - Musica che resta", "4. Loredana Bertè - Cosa ti aspetti da me", "5. Simone Cristicchi - Abbi cura di me", "6. Daniele Silvestri y Rancore - Argentovivo", "7. Irama - La ragazza con il cuore di latta", "8. Arisa - Mi sento bene", "9. Achille Lauro - Rolls Royce", "10. Enrico Nigiotti - Nonno Hollywood", "11. Boomdabash - Per un milione", "12. Ghemon - Rose viola", "13. Ex-Otago - Solo una canzone", "14. Motta - Dov'è l'Italia", "15. Francesco Renga - Aspetto che torni", "16. Paola Turci - L'ultimo ostacolo", "17. The Zen Circus - L'amore è una dittatura", "18. Federica Carta y Shade - Senza farlo apposta", "19. Nek - Mi farò trovare pronto", "20. Negrita - I ragazzi stanno bene", "21. Patty Pravo y Briga - Un po' come la vita", "22. Anna Tatangelo - Le nostre anime di notte", "23. Einar - Parole nuove", "24. Nino D'Angelo y Livio Cori - Un'altra luce"],
        "2020": ["1. Diodato - Fai rumore", "2. Francesco Gabbani - Viceversa", "3. Pinguini Tattici Nucleari - Ringo Starr", "4. Le Vibrazioni - Dov'è", "5. Piero Pelù - Gigante", "6. Tosca - Ho amato tutto", "7. Elodie - Andromeda", "8. Achille Lauro - Me ne frego", "9. Irene Grandi - Finalmente io", "10. Rancore - Eden", "11. Raphael Gualazzi - Carioca", "12. Levante - Tikibombom", "13. Anastasio - Rosso di rabbia", "14. Alberto Urso - Il sole ad est", "15. Marco Masini - Il confronto", "16. Paolo Jannacci - Voglio parlarti adesso", "17. Rita Pavone - Niente (Resilienza 74)", "18. Michele Zarrillo - Nell'estasi o nel fango", "19. Enrico Nigiotti - Baciami adesso", "20. Giordana Angi - Come mia madre", "21. Elettra Lamborghini - Musica (e il resto scompare)", "22. Junior Cally - No grazie", "23. Riki - Lo sappiamo entrambi", "- Bugo e Morgan - Sincero (descaliﬁcado)"],
        "2021": ["1. Måneskin - Zitti e buoni", "2. Francesca Michielin y Fedez - Chiamami per nome", "3. Ermal Meta - Un milione di cose da dirti", "4. Colapesce Dimartino - Musica leggerissima", "5. Irama - La genesi del tuo colore", "6. Willie Peyote - Mai dire mai (la locura)", "7. Annalisa - Dieci", "8. Madame - Voce", "9. Orietta Berti - Quando ti sei innamorato", "10. Arisa - Potevi fare di più", "11. La Rappresentante di Lista - Amare", "12. Extraliscio y Davide Toﬀolo - Bianca luce nera", "13. Lo Stato Sociale - Combat pop", "14. Noemi - Glicine", "15. Malika Ayane - Ti piaci così", "16. Fulminacci - Santa Marinella", "17. Max Gazzè - Il farmacista", "18. Fasma - Parlami", "19. Gaia - Cuore amaro", "20. Coma_Cose - Fiamme negli occhi", "21. Ghemon - Momento perfetto", "22. Francesco Renga - Quando trovo te", "23. Gio Evan - Arnica", "24. Bugo - E invece sì", "25. Aiello - Ora", "26. Random - Torno a te"],
        "2022": ["1. Mahmood e Blanco - Brividi", "2. Elisa - O forse sei tu", "3. Gianni Morandi - Apri tutte le porte", "4. Irama - Ovunque sarai", "5. Sangiovanni - Farfalle", "6. Emma - Ogni volta è così", "7. La Rappresentante di Lista - Ciao ciao", "8. Massimo Ranieri - Lettera di là dal mare", "9. Dargen D'Amico - Dove si balla", "10. Michele Bravi - Inverno dei ﬁori", "11. Matteo Romano - Virale", "12. Fabrizio Moro - Sei tu", "13. AKA 7even - Perfetta così", "14. Achille Lauro con Harlem Gospel Choir - Domenica", "15. Noemi - Ti amo non lo so dire", "16. Ditonellapiaga e Rettore - Chimica", "17. Rkomi - Insuperabile", "18. Iva Zanicchi - Voglio amarti", "19. Giovanni Truppi - Tuo padre, mia madre, Lucia", "20. Highsnob e Hu - Abbi cura di te", "21. Yuman - Ora e qui", "22. Le Vibrazioni - Tantissimo", "23. Giusy Ferreri - Miele", "24. Ana Mena - Duecentomila ore", "25. Tananai - Sesso occasionale"],
        "2023": ["1. Marco Mengoni - Due vite", "2. Lazza - Cenere", "3. Mr. Rain - Supereroi", "4. Ultimo - Alba", "5. Tananai - Tango", "6. Giorgia - Parole dette male", "7. Madame - Il bene nel male", "8. Rosa Chemical - Made in Italy", "9. Elodie - Due", "10. Colapesce Dimartino - Splash", "11. Modà - Lasciami", "12. Gianluca Grignani - Quando ti manca il ﬁato", "13. Coma_Cose - L'addio", "14. Ariete - Mare di guai", "15. LDA - Se poi domani", "16. Articolo 31 - Un bel viaggio", "17. Paola & Chiara - Furore", "18. Leo Gassmann - Terzo cuore", "19. Mara Sattei - Duemilaminuti", "20. Colla Zio - Non mi va", "21. Cugini di Campagna - Lettera 22", "22. gIANMARIA - Mostro", "23. Levante - Vivo", "24. Olly - Polvere", "25. Anna Oxa - Sali (canto dell'anima)", "26. Will - Stupido", "27. Shari - Egoista", "28. Sethu - Cause perse"],
        "2024": ["1. Angelina Mango - La noia", "2. Geolier - I p' me, tu p' te", "3. Annalisa - Sinceramente", "4. Ghali - Casa mia", "5. Irama - Tu no", "6. Mahmood - Tuta gold", "7. Loredana Bertè - Pazza", "8. Il Volo - Capolavoro", "9. Alessandra Amoroso - Fino a qui", "10. Alfa - Vai!", "11. Gazzelle - Tutto qui", "12. Il Tre - Fragili", "13. Diodato - Ti muovi", "14. Emma - Apnea", "15. Fiorella Mannoia - Mariposa", "16. The Kolors - Un ragazzo una ragazza", "17. Mr. Rain - Due altalene", "18. Santi Francesi - L'amore in bocca", "19. Negramaro - Ricominciamo tutto", "20. Dargen D'Amico - Onda alta", "21. Ricchi e Poveri - Ma non tutta la vita", "22. BigMama - La rabbia non ti basta", "23. Rose Villain - Click boom!", "24. Clara - Diamanti grezzi", "25. Renga Nek - Pazzo di te", "26. Maninni - Spettacolare", "27. La Sad - Autodistruttivo", "28. Bnkr44 - Governo punk", "29. Sangiovanni - Finiscimi", "30. Fred De Palma - Il cielo non ci vuole"],
        "2025": ["1. Olly - Balorda nostalgia", "2. Lucio Corsi - Volevo essere un duro", "3. Brunori Sas - L'albero delle noci", "4. Fedez - Battito", "5. Simone Cristicchi - Quando sarai piccola", "6. Giorgia - La cura per me", "7. Achille Lauro - Incoscienti giovani", "8. Francesco Gabbani - Viva la vita", "9. Irama - Lentamente", "10. Coma_Cose - Cuoricini", "11. Bresh - La tana del granchio", "12. Elodie - Dimenticarsi alle 7", "13. Noemi - Se t'innamori muori", "14. The Kolors - Tu con chi fai l'amore", "15. Rocco Hunt - Mille vote ancora", "16. Willie Peyote - Grazie ma no grazie", "17. Sarah Toscano - Amarcord", "18. Shablo con Guè, Joshua e Tormento - La mia parola", "19. Rose Villain - Fuorilegge", "20. Joan Thiele - Eco", "21. Francesca Michielin - Fango in paradiso", "22. Modà - Non ti dimentico", "23. Massimo Ranieri - Tra le mani un cuore", "24. Serena Brancale - Anema e core", "25. Tony Eﬀe - Damme 'na mano", "26. Gaia - Chiamo io chiami tu", "27. Clara - Febbre", "28. Rkomi - Il ritmo delle cose", "29. Marcella Bella - Pelle diamante", "- Emis Killa - Demoni (descaliﬁcado)"]
    };

    // --- VARIABLES Y CONSTANTES DEL DOM ---
    const votingSectionsContainer = document.getElementById('voting-sections');
    const prevBtn = document.getElementById('prev-btn');
    const nextBtn = document.getElementById('next-btn');
    const userInfo = document.getElementById('user-info');
    const form = document.getElementById('sanremo-form');
    const sectionTitle = document.getElementById('section-title');
    const navButtons = document.getElementById('navigation-buttons');

    let currentSection = 0;
    const totalSections = 10;
    const points = [1, 2, 3, 4, 5, 6, 7, 8, 10, 12];

    // --- FUNCIÓN PARA CREAR LAS SECCIONES DE VOTACIÓN ---
    function createVotingSections() {
        let allSectionsHTML = '';
        for (let i = 0; i < totalSections; i++) {
            allSectionsHTML += `
                <div class="voting-section ${i === 0 ? '' : 'hidden'}" id="section-${i}">
                    <label for="year-${i}">Año:</label>
                    <select id="year-${i}" name="year-${i}" required>
                        <option value="">Selecciona un año</option>
                        ${Object.keys(songsData).sort((a,b) => b-a).map(year => `<option value="${year}">${year}</option>`).join('')}
                    </select>
                    
                    <label for="song-${i}">Canción:</label>
                    <select id="song-${i}" name="song-${i}" required>
                        <option value="">Primero selecciona un año</option>
                    </select>
                </div>
            `;
        }
        votingSectionsContainer.innerHTML = allSectionsHTML;
    }

    // --- FUNCIÓN PARA ACTUALIZAR LAS CANCIONES SEGÚN EL AÑO ---
    function updateSongs(yearSelect, songSelect) {
        const selectedYear = yearSelect.value;
        songSelect.innerHTML = '<option value="">Selecciona una canción</option>'; // Limpiar y poner placeholder
        if (selectedYear && songsData[selectedYear]) {
            songsData[selectedYear].forEach(song => {
                const option = document.createElement('option');
                option.value = song;
                option.textContent = song;
                songSelect.appendChild(option);
            });
        }
    }
    
    // --- FUNCIÓN PARA MOSTRAR LA SECCIÓN ACTUAL ---
    function showSection(index) {
        document.querySelectorAll('.voting-section').forEach((section, i) => {
            section.classList.toggle('hidden', i !== index);
        });

        // TÍTULO DE SECCIÓN MODIFICADO
        sectionTitle.textContent = `${points[index]} Puntos`;
        prevBtn.classList.toggle('hidden', index === 0);
        
        if (index === totalSections - 1) {
            nextBtn.classList.add('hidden');
            userInfo.classList.remove('hidden');
            navButtons.classList.add('hidden');
        } else {
            nextBtn.classList.remove('hidden');
            userInfo.classList.add('hidden');
            navButtons.classList.remove('hidden');
        }
    }

    // --- INICIALIZACIÓN Y EVENT LISTENERS ---
    createVotingSections();

    // Añadir listeners a todos los select de año
    for (let i = 0; i < totalSections; i++) {
        const yearSelect = document.getElementById(`year-${i}`);
        const songSelect = document.getElementById(`song-${i}`);
        yearSelect.addEventListener('change', () => updateSongs(yearSelect, songSelect));
    }

    nextBtn.addEventListener('click', () => {
        if (currentSection < totalSections - 1) {
            currentSection++;
            showSection(currentSection);
        }
    });

    prevBtn.addEventListener('click', () => {
        if (currentSection > 0) {
            currentSection--;
            showSection(currentSection);
        }
    });

    form.addEventListener('submit', function(e) {
        e.preventDefault();
        const submitButton = document.getElementById('submit-btn');
        submitButton.disabled = true;
        submitButton.textContent = 'Enviando...';

        // ===================================================================
        // IMPORTANTE: REEMPLAZA ESTA URL CON LA TUYA DE GOOGLE APPS SCRIPT
        const scriptURL = 'https://script.google.com/macros/s/AKfycbyeqkZZtTtUmtJY49K6ggBXa-h4l-PxucnYC1f-ZBhYkV3U7FLb7YkU1MLBtGV3-psJ/exec';
        // ===================================================================
        
        fetch(scriptURL, { method: 'POST', body: new FormData(form)})
            .then(response => {
                // ALERTA MODIFICADA
                alert('¡Gracias por participar en Sanremo100!');
                form.reset();
                currentSection = 0;
                // Resetear todos los select de canciones
                 for (let i = 0; i < totalSections; i++) {
                    document.getElementById(`song-${i}`).innerHTML = '<option value="">Primero selecciona un año</option>';
                 }
                showSection(currentSection); // Volver al inicio
                submitButton.disabled = false;
                submitButton.textContent = 'Enviar Votos';
            })
            .catch(error => {
                console.error('Error!', error.message);
                alert('Hubo un error al enviar tus votos. Por favor, inténtalo de nuevo.');
                submitButton.disabled = false;
                submitButton.textContent = 'Enviar Votos';
            });
    });

    // Mostrar la primera sección al cargar
    showSection(0);
});