document.addEventListener('DOMContentLoaded', function() {

    // --- BASE DE DATOS DE CANCIONES INTEGRADA ---
    const songsData = {
        "1951": ["Nilla Pizzi – Grazie dei fiori", "Nilla Pizzi y Achille Togliani – La luna si veste d’argento", "Achille Togliani – Serenata a nessuno", "Achille Togliani y Duo Fasano – Al mercato di Pizzighettone", "Duo Fasano – La cicogna distratta", "Nilla Pizzi y Duo Fasano – La margherita", "Nilla Pizzi y Achille Togliani – L’eco fra gli abeti", "Achille Togliani y Duo Fasano – Togliani Famme durmì", "Achille Togliani – Sedici anni", "Duo Fasano – Sotto il mandorlo"],
        "1952": ["Nilla Pizzi – Vola colomba", "Nilla Pizzi – Papaveri e papere", "Nilla Pizzi – Una donna prega", "Oscar Carboni – Madonna delle rose", "Gino Latilla – Un disco dall’Italia", "Gino Latilla – L’attesa", "Oscar Carboni – Perché le donne belle", "Achille Togliani – Vecchie mura", "Achille Togliani – Libro di novelle", "Nilla Pizzi y Achille Togliani – Nel regno dei sogni"],
        "1953": ["Carla Boni / Flo Sandon’s – Viale d’autunno", "Nilla Pizzi y Doppio Quintetto Vocale / Teddy Reno y Quartetto Star - Campanaro", "Giorgio Consolini / Gino Latilla & Doppio Quintetto Vocale – Vecchio scarpone", "Achille Togliani / Teddy Reno – Lasciami cantare una canzone", "Gino Latilla / Giorgio Consolini – Vecchia villa comunale", "Achille Togliani / Katyna Ranieri – No, Pierrot", "Carla Boni / Quartetto Star – Il passerotto", "Nilla Pizzi y Doppio Quintetto Vocale / Teddy Reno y Quartetto Star – Sussurrando buonanotte", "Gino Latilla y Doppio Quintetto Vocale / Giorgio Consolini – Tamburino del reggimento", "Nilla Pizzi y Doppio Quintetto Vocale / Teddy Reno y Quartetto Star – Papà pacifico"],
        "1954": ["Gino Latilla / Giorgio Consolini – Tutte le mamme", "Katyna Ranieri / Achille Togliani – Canzone da due soldi", "Gino Latilla / Franco Ricci – …E la barca tornò sola", "Vittoria Mongardi / Natalino Otto – Notturno… (per chi non ha nessuno)", "Carla Boni / Flo Sandon’s – Non è mai troppo tardi", "Vittoria Mongardi y Duo Fasano / Quartetto Cetra – Aveva un bavero", "Gino Latilla y Duo Fasano / Katyna Ranieri & Giorgio Consolini – Sotto l’ombrello", "Achille Togliani / Natalino Otto – Mogliettina", "Achille Togliani / Flo Sandon’s – Con te", "Natalino Otto / Achille Togliani – Donnina sola"],
        "1955": ["Claudio Villa / Tullio Pane – Buongiorno tristezza", "Claudio Villa / Tullio Pane – Il torrente", "Natalino Otto y Trio Aurora / Nuccia Bongiovanni, Bruno Pallesi y Radio Boys – Canto nella valle", "Narciso Parigi / Claudio Villa – Incantatella", "Antonio Basurto / Gianni Ravera – Un cuore", "Jula De Palma / Marisa Colomber – L’ombra", "Natalino Otto y Trio Aurora / Narciso Parigi y Radio Boys – Ci ciu ci (cantava un usignol)", "Antonio Basurto / Natalino Otto – Una fotograﬁa nella cornice"],
        "1956": ["Franca Raimondi – Aprite le finestre", "Tonina Torrielli – Amami se vuoi", "Luciana Gonzales – La vita è un paradiso di bugie", "Tonina Torrielli – Il cantico del cielo", "Ugo Molinari – La colpa fu", "Tonina Torrielli / Katyna Ranieri – Il bosco innamorato", "Ugo Molinari – Albero caduto", "Gianni Marzocchi – Musetto (la più bella sei tu)", "Ugo Molinari – Nota per nota", "Ugo Molinari – Due teste sul cuscino"],
        "1957": ["Claudio Villa / Nunzio Gallo – Corde della mia chitarra", "Claudio Villa / Giorgio Consolini – Usignolo", "Gino Latilla / Tonina Torrielli – Scusami", "Carla Boni, Gino Latilla y Duo Fasano / Gloria, Christian y Poker di Voci – Casetta in Canadà", "Giorgio Consolini / Claudio Villa – Cancello tra le rose", "Natalino Otto y Poker di Voci / Gino Latilla y Claudio Villa – Il pericolo numero uno", "Tina Allori / Tonina Torrielli – Intorno a te (è sempre primavera)", "Carla Boni / Nunzio Gallo – Per una volta ancora", "Gino Latilla y Duo Fasano / Natalino Otto y Poker di Voci – Un filo di speranza", "Carla Boni y Duo Fasano / Gloria Christian, Natalino Otto y Poker di Voci – Le trote blu"],
        "1958": ["Domenico Modugno / Johnny Dorelli – Nel blu dipinto di blu", "Nilla Pizzi / Tonina Torrielli – L’edera", "Gino Latilla / Nilla Pizzi – Amare un’altra", "Giorgio Consolini / Claudio Villa – Campana di Santa Lucia", "Nilla Pizzi / Claudio Villa – Giuro d’amarti così", "Carla Boni y Gino Latilla / Aurelio Fierro y Gloria Christian – Timida serenata", "Claudio Villa y Duo Fasano / Aurelio Fierro y Trio Joice – Fragole e cappellini", "Carla Boni y Gino Latilla / Natalino Otto – Non potrai dimenticare", "Cristina Jorio / Tonina Torrielli – Mille volte", "Johnny Dorelli / Natalino Otto – Fantastica"],
        "1959": ["Domenico Modugno / Johnny Dorelli – Piove (ciao ciao bambina)", "Gino Latilla / Arturo Testa – Io sono il vento", "Tedy Reno / Achille Togliani – Conoscerti", "Jula De Palma / Tonina Torrielli – Tua", "Aurelio Fierro / Teddy Reno – Lì per lì", "Fausto Cigliano / Nilla Pizzi – Sempre con te", "Natalino Otto / Aurelio Fierro – Avevamo la stessa età", "Betty Curtis / Wilma De Angelis – Nessuno", "Johnny Dorelli y Betty Curtis / Gino Latilla y Claudio Villa – Una marcia in fa", "Claudio Villa / Betty Curtis – Un bacio sulla bocca"],
        "1960": ["Tony Dallara / Renato Rascel – Romantica", "Domenico Modugno / Teddy Reno – Libero", "Wilma De Angelis / Joe Sentieri – Quando vien la sera", "Nilla Pizzi / Tonina Torrielli – Colpevole", "Joe Sentieri / Sergio Bruni – È mezzanotte", "Giorgio Consolini / Sergio Bruni – Il mare", "Jula De Palma / Tony Dallara – Noi", "Teddy Reno / Mina – È vero", "Fausto Cigliano / Irene D’Areni – Splende il sole", "Johnny Dorelli / Jula De Palma – Notte mia"],
        "1961": ["Betty Curtis / Luciano Tajoli – Al di là", "Adriano Celentano / Little Tony – 24 mila baci", "Milva / Gino Latilla – Il mare nel cassetto", "Mina / Nelly Fioramonti – Io amo tu ami", "Mina / Jenny Luna – Le mille bolle blu", "Pino Donaggio / Teddy Reno – Come sinfonia", "Arturo Testa / Tonina Torrielli – Febbre di musica", "Teddy Reno / Sergio Bruni – Mandolino mandolino", "Sergio Bruni / Rocco Granata – Carolina, dai", "Gino Paoli / Tony Dallara – Un uomo vivo", "Umberto Bindi / Miranda Martino – Non mi dire chi sei", "Joe Sentieri / Fausto Cigliano – Lei"],
        "1962": ["Domenico Modugno / Claudio Villa – Addio… addio…", "Sergio Bruni / Milva – Tango italiano", "Sergio Bruni / Ernesto Bonino – Gondolì gondolà", "Tony Renis / Emilio Pericoli – Quando quando quando", "Milva / Miriam Del Mare – Stanotte al luna park", "Gino Bramieri / Aurelio Fierro – Lui andava a cavallo", "Arturo Testa / Jolanda Rossin – Un’anima leggera", "Joe Sentieri / Aurelio Fierro – Cipria di sole", "Tonina Torrielli / Aura D’Angelo – Aspettandoti", "Johnny Dorelli / Betty Curtis – Buongiorno amore", "Flo Sandon’s / Mario D’Alba – Passa il tempo", "Nunzio Gallo / Rocco Montana – Inventiamo la vita"],
        "1963": ["Tony Renis/ Emilio Pericoli - Uno per tutte", "Claudio Villa/ Eugenia Foligatti - Amor, mon amour, my love", "Pino Donaggio/ Cocky Mazzetti - Giovane giovane", "Johnny Dorelli/ Wilma De Angelis - Non costa niente", "Milva/ Luciano Tajoli - Ricorda", "Tonina Torrielli/ Eugenia Foligatti - Perdonarsi in due", "Claudio Villa/ Aurelio Fierro - Occhi neri e cielo blu", "Emilio Pericoli/ Sergio Bruni - Sull’acqua", "Aura D’angelo/ Arturo Testa - Tu venisti dal mare", "Milva/ Gianni Lacommare - Non sapevo"],
        "1964": ["Gigliola Cinquetti / Patricia Carli – Non ho l'età (Per amarti)", "Domenico Modugno / Frankie Laine – Che me ne importa a me", "Tony Dallara / Ben E. King - Come potrei domenticarti", "Gino Paoli / Antonio Prieto – Ieri ho incontrato mia madre", "Fabrizio Ferretti / Gil Fields & The Fraternity Brothers – La prima che incontro", "Pino Donaggio / Frankie Avalon – Motivo d'amore", "Roby Ferrante / Paul Anka – Ogni volta", "Little Tony / Gene Pitney – Quando vedrai la mia ragazza", "Bruno Filippini / Gil Fields & The Fraternity Brothers – Sabato sera", "Remo Germani / Nino Tempo & April Stevens – Stasera no no no", "Robertino / Bobby Rydell – Un bacio piccolissimo", "Bobby Solo / Frankie Laine – Una lacrima sul viso"],
        "1965": ["Bobby Solo / The New Christy Minstrels – Se piangi, se ridi", "Ornella Vanoni / Udo Jürgens – Abbracciami forte", "Nicola Di Bari / Gene Pitney – Amici miei", "Fred Bongusto / Kiki Dee – Aspetta domani", "Gigliola Cinquetti / Connie Francis – Ho bisogno di vederti", "Betty Curtis / Petula Clark – Invece no", "Pino Donaggio / Jody Miller – Io che non vivo (senza te)", "Bruno Filippini / Yukari Ito – L'amore ha i tuoi occhi", "Wilma Goich / The New Christy Minstrels – Le colline sono in fiore", "Remo Germani / Le Amiche – Prima o poi", "Vittorio Inzaina / Les Surfs – Si vedrà", "Milva / Bernd Spier – Vieni con noi"],
        "1966": ["Domenico Modugno / Gigliola Cinquetti – Dio, come ti amo", "Caterina Caselli / Gene Pitney – Nessuno mi può giudicare", "Wilma Goich / Les Surfs – In un fiore", "Pino Donaggio / Claudio Villa – Una casa in cima al mondo", "Anna Identici / The New Christy Minstrels – Una rosa da Vienna", "Orietta Berti / Ornella Vanoni – Io ti darò di più", "Giorgio Gaber / Pat Boone – Mai mai mai Valentina", "Edoardo Vianello / Françoise Hardy – Parlami di te", "Sergio Endrigo / Chad & Jeremy – Adesso sì", "Milva / Richard Anthony – Nessuno di voi", "Peppino Gagliardi / Pat Boone – Se tu non fossi qui", "Remo Germani / Les Surfs – Così come viene", "Iva Zanicchi / Vic Dana – La notte dell'addio", "I Ribelli / The New Christy Minstrels – A la buena de Dios"],
        "1967": ["Iva Zanicchi / Claudio Villa – Non pensare a me", "Annarita Spinaci / Les Surfs – Quando dico che ti amo", "I Giganti / The Bachelors – Proposta", "Ornella Vanoni / Mario Guarnera – La musica è finita", "Orietta Berti / Les compagnons de la Chanson – Io, tu e le rose", "Lucio Dalla / The Rokes – Bisogna saper perdere", "Sergio Endrigo / Memo Remigi – Dove credi di andare", "Gian Pieretti / Antoine – Pietre", "Johnny Dorelli / Don Backy – L'immensità", "Little Tony / Mario Zelinotti – Cuore matto", "Pino Donaggio / Carmen Villani – Io per amore", "Wilma Goich / The Bachelors – Per vedere quant'è grande il mondo", "Giorgio Gaber / Remo Germani – E allora dai", "Gianni Pettenati / Gene Pitney – La rivoluzione"],
        "1968": ["Sergio Endrigo / Roberto Carlos – Canzone per te", "Ornella Vanoni / Marisa Sannia – Casa bianca", "Adriano Celentano / Milva – Canzone", "Fausto Leali / Wilson Pickett – Deborah", "Gianni Pettenati / Antoine – La tramontana", "Anna Identici / The Sandpipers – Quando m’innamoro", "Massimo Ranieri / Il Giganti – Da bambino", "Gigliola Cinquetti / Giuliana Valci – Sera", "Al Bano / Bobbie Gentry – La siepe", "Little Tony / Mario Guarnera – Un uomo piange solo per amore", "Wilma Goich / Dino – Gli occhi miei", "Annarita Spinaci / Yoko Kishi – Stanotte sentirai una canzone", "Louis Armstrong / Lara Saint Paul – Mi va di cantare", "Tony Del Monaco / Dionne Warwick – La voce del silenzio"],
        "1969": ["Bobby Solo / Iva Zanicchi – Zingara", "Sergio Endrigo / Mary Hopkin – Lontano dagli occhi", "Don Backy / Milva – Un sorriso", "Fausto Leali / Tony Del Monaco – Un’ora fa", "Nada / The Rokes – Che freddo fa", "Gigliola Cinquetti / France Gall – La pioggia", "The Showmen / Mal – Tu sei bella come sei", "Caterina Caselli / Johnny Dorelli – Il gioco dell’amore", "Lucio Battisti / Wilson Pickett – Un’avventura", "Orietta Berti / Massimo Ranieri – Quando l’amore diventa poesia", "Carmen Villani / Alessandra Casaccia – Piccola piccola", "Little Tony / Mario Zelinotti – Bada bambina", "Rita Pavone / Dik Dik – Zucchero", "Riccardo Del Turco / Antoine – Cosa hai messo nel caffè"],
        "1970": ["Adriano Celentano / Claudia Mori – Chi non lavora non fa l'amore", "Nicola Di Bari / Ricchi e Poveri – La prima cosa bella", "Sergio Endrigo / Iva Zanicchi – L'arca di Noè", "Ornella Vanoni / Camaleonti – Eternità", "Little Tony / Patty Pravo – La spada nel cuore", "Bobby Solo / Gigliola Cinquetti – Romantico blues", "Nada / Rosalino Cellamare – Pa' diglielo a ma'", "Anna Identici / Antoine – Taxi", "Luciano Tajoli / Mal – Sole, pioggia e vento", "Mario Tessuto / Orietta Berti – Tipitipitì", "Gianni Nazzaro / Marisa Sannia – L'amore è una colomba", "Carmen Villani / Fausto Leali – Hippy", "Sergio Leonardi / Tony Renis – Canzone blu", "Caterina Caselli / Nino Ferrer – Re di cuori"],
        "1971": ["Nada / Nicola Di Bari – Il cuore è uno zingaro", "Ricchi e Poveri / José Feliciano – Che sarà", "Lucio Dalla / l'Equipe 84 – 4 marzo 1943", "Donatello / Marisa Sannia – Com'è dolce la sera", "Adriano Celentano / Coro Alpino Milanese – Sotto le lenzuola", "Domenico Modugno / Carmen Villani – Come stai?", "Don Backy / Gianni Nazzaro – Bianchi cristalli sereni", "Al Bano / Aguaviva – 13, storia d'oggi", "Gigliola Cinquetti / Ray Conniﬀ – Rose nel buio", "Caterina Caselli / Dik Dik – Ninna nanna (Cuore mio)", "Pino Donaggio / Peppino Di Capri – L'ultimo romantico", "Little Tony / Formula 3 – La folle corsa", "Sergio Endrigo / New Trolls – Una storia", "Sergio Menegale / Wallace Collection – Il sorriso il paradiso"],
        "1972": ["Nicola Di Bari – I giorni dell'arcobaleno", "Peppino Gagliardi – Come le viole", "Nada – Il re di denari", "Gianni Morandi – Vado a lavorare", "Gianni Nazzaro – Non voglio innamorarmi mai", "Delirium – Jesahel", "Marcella Bella – Montagne verdi", "Lucio Dalla – Piazza Grande", "Gigliola Cinquetti – Gira l'amore", "Donatello – Ti voglio", "Ricchi e Poveri – Un diadema di ciliegie", "Milva – Mediterraneo", "Lara Saint Paul – Se non fosse fra queste mie braccia lo inventerei", "Domenico Modugno – Un calcio alla città"],
        "1973": ["Peppino Di Capri – Un grande amore e niente più", "Peppino Gagliardi – Come un ragazzino", "Milva – Da troppo tempo", "Ricchi e Poveri – Dolce frutto", "Gilda Giuliani – Serena", "Wess y Dori Ghezzi – Tu nella mia vita", "Roberto Vecchioni – L'uomo che si gioca il cielo a dadi", "Fausto Leali – La bandiera di sole", "Umberto Balsamo – Amore mio", "Anna Identici – Mi son chiesta tante volte", "Camaleonti – Come sei bella", "Donatello – Tu giovane amore mio", "Memo Remigi – Il mondo è qui", "Alessandro – Tre minuti di ricordi", "Lionello – Straniera straniera", "Lara Saint Paul – Una casa grande"],
        "1974": ["Iva Zanicchi – Ciao, cara come stai?", "Domenico Modugno – Questa è la mia vita", "Orietta Berti – Occhi rossi", "Anna Melato – Sta piovendo dolcemente", "Emanuela Cortesi – Il mio volo bianco", "Gilda Giuliani – Senza titolo", "I Domodossola – Se hai paura", "Les Charlots – Mon ami tango", "Valentina Greco – Notte dell’estate", "Nicola Di Bari – Il matto del villaggio", "Mouth & MacNeal – Ah! L’amore", "Gianni Nazzaro – A modo mio", "Al Bano – In controluce", "Mino Reitano – Innamorati", "Rosanna Fratello – Un po’ di coraggio", "Little Tony – Cavalli bianchi", "Milva – Monica delle bambole", "Middle of the Road – Sole giallo"],
        "1975": ["Gilda – Ragazza del sud", "Angela Luce – Ipocrisia", "Rosanna Fratello – Va' speranza va'", "Valentina Greco – Un grande addio", "Laura – E poi e poi", "Franco e le Piccole Donne – Come Humphrey Bogart"],
        "1976": ["Peppino Di Capri – Non lo faccio più", "Wess & Dori Ghezzi – Come stai, con chi sei", "Sandro Giacobbe – Gli occhi di tua madre", "Albatros – Volo AZ 504", "Paolo Frescura – Due anelli", "Drupi – Sambariò", "Carlo Gigli – Più forte", "Daniel Sentacruz Ensemble – Linda bella Linda", "Gli Opera – L'ho persa ancora", "Camaleonti – Cuore di vetro", "Orietta Berti – Omar", "La Strana Società – Andiamo via", "Ricchi e Poveri con I Nostri Figli – Due storie dei musicanti", "Patrizio Sandrelli – Piccola donna addio", "Sergio Endrigo – Quando c'era il mare", "Miko – Signora tu", "Profeti – Cercati un'anima", "La Nuova Gente – Che sarei"],
        "1977": ["Homo Sapiens – Bella da morire", "Collage – Tu mi rubi l'anima", "I Santo California – Monica", "Umberto Napolitano – Con te ci sto", "Santino Rocchetti – Dedicato a te", "Daniela Davoli – E invece con te", "Albatros – Gran Premio", "Leano Morelli – Io ti porterei", "Matia Bazar – Ma perché", "Il Giardino dei Semplici – Miele", "Donatella Rettore - Carmela", "La Strana Società - Tesoro mio"],
        "1978": ["Matia Bazar – ...e dirsi ciao", "Anna Oxa – Un'emozione da poco", "Rino Gaetano – Gianna", "Ciro Sebastianelli – Il buio e tu", "Anselmo Genovese – Tu sola", "Santino Rocchetti – Armonia e poesia", "Schola Cantorum – Il mio amore", "Laura Luca – Domani domani", "Daniel Sentacruz Ensemble – 1/2 notte"],
        "1979": ["Mino Vergnaghi – Amare", "Enzo Carella – Barbara", "I Camaleonti – Quell'attimo in più", "Collage – La gente parla", "Enrico Beruschi – Sarà un fiore", "Franco Fanigliulo – A me mi piace vivere alla grande", "Lorella Pescerelli – New York", "Kim & The Cadillacs – C’era un’atmosfera", "Umberto Napolitano – Bimba mia", "Pandemonium – Tu fai schifo sempre", "Antoine – Nocciolino", "Grimm – Liana"],
        "1980": ["Toto Cutugno – Solo noi", "Enzo Malepasso – Ti voglio bene", "Pupo – Su di noi", "Gianni Morandi – Mariù", "La Bottega dell'Arte – Più di una canzone", "Sally Oldfield – I Sing for You", "Stefano Rosso – L'italiano", "Leroy Gomez – Tu mi manchi dentro", "Decibel – Contessa"],
        "1981": ["Alice – Per Elisa", "Loretta Goggi – Maledetta primavera", "Dario Baldan Bembo – Tu cosa fai stasera?", "Luca Barbarossa – Roma spogliata", "Ricchi e Poveri – Sarà perché ti amo", "Paolo Barabani – Hop hop somarello", "Marinella – Ma chi te lo fa fare", "Michele Zarrillo – Su quel pianeta libero", "Marcella – Pensa per te", "Passengers – Midnight", "Eduardo De Crescenzo – Ancora", "Fiorella Mannoia – Caffè nero bollente"],
        "1982": ["Riccardo Fogli – Storie di tutti i giorni", "Al Bano Carrisi e Romina Power – Felicità", "Drupi – Soli", "Giuseppe Cionfoli – Solo grazie", "Christian – Un’altra vita un altro amore", "Milk & Coffee - Quando incontri l’amore", "Mia Martini – E non finisce mica il cielo", "Anna Oxa – Io no", "Vasco Rossi – Vado al massimo", "Zucchero – Una notte che vola via"],
        "1983": ["Tiziana Rivale – Sarà quel che sarà", "Donatella Milani – Volevo dirti", "Dori Ghezzi – Margherita non lo sa", "Matia Bazar – Vacanze romane", "Toto Cutugno – L'italiano", "Fiordaliso – Oramai", "Gianni Morandi – La mia nemica amatissima", "Amii Stewart – Working Late Tonight", "Vasco Rossi – Vita spericolata", "Pupo – Cieli azzurri", "Amedeo Minghi – 1950"],
        "1984": ["Al Bano y Romina Power – Ci sarà", "Toto Cutugno – Serenata", "Christian – Cara", "Pupo – Un amore grande", "Fiordaliso – Non voglio mica la luna", "Mario Castelnuovo – Nina", "Anna Oxa – Non scendo", "Drupi – Regalami un sorriso", "Iva Zanicchi – Chi (Mi darà)", "Patty Pravo – Per una bambola", "Fiorella Mannoia – Come si cambia", "Enrico Ruggeri – Nuovo swing"],
        "1985": ["Ricchi e Poveri – Se m'innamoro", "Luis Miguel – Noi, ragazzi di oggi", "Gigliola Cinquetti – Chiamalo amore", "Riccardo Fogli – Sulla buona strada", "Christian – Notte serena", "Eros Ramazzotti – Una storia importante", "Anna Oxa – A lei", "Fiordaliso – Il mio angelo", "Peppino di Capri – E mo' e mo'", "Matia Bazar – Souvenir", "Zucchero Fornaciari & Randy Jackson Band - Donne"],
        "1986": ["Eros Ramazzotti – Adesso tu", "Renzo Arbore – Il clarinetto", "Marcella – Senza un briciolo di testa", "Toto Cutugno – Azzurra malinconia", "Anna Oxa – È tutto un attimo", "Orietta Berti – Futuro", "Nino D'Angelo – Vai", "Fred Bongusto – Cantare", "Loredana Bertè – Re", "Fiordaliso – Fatti miei", "Mango – Lei verrà", "Enrico Ruggeri – Rien ne va plus", "Luca Barbarossa – Via Margutta", "Zucchero Fornaciari - Canzone triste"],
        "1987": ["Gianni Morandi, Enrico Ruggeri y Umberto Tozzi – Si può dare di più", "Toto Cutugno – Figli", "Al Bano y Romina Power – Nostalgia canaglia", "Fausto Leali – Io amo", "Peppino Di Capri – Il sognatore", "Marcella – Tanti auguri", "Ricchi e Poveri – Canzone d'amore", "Fiorella Mannoia – Quello che le donne non dicono", "Luca Barbarossa – Come dentro un film", "Mango – Dal cuore in poi", "Nada - Bolero"],
        "1988": ["Massimo Ranieri – Perdere l'amore", "Toto Cutugno – Emozioni", "Luca Barbarossa – L'amore rubato", "Marcella Bella – Dopo la tempesta", "Fausto Leali – Mi manchi", "Mino Reitano – Italia", "Anna Oxa – Quando nasce un amore", "Fiordaliso & Claudio Cabrini – Per noi", "Ricchi e Poveri – Nascerà Gesù", "Fiorella Mannoia – Le notti di maggio", "Raf – Inevitabile follia", "Tullio De Piscopo – Andamento lento", "Ron – Il mondo avrà una grande anima"],
        "1989": ["Anna Oxa y Fausto Leali – Ti lascerò", "Toto Cutugno – Le mamme", "Al Bano y Romina Power – Cara terra mia", "Riccardo Fogli – Non finisce così", "Jovanotti – Vasco", "Fiordaliso – Se non avessi te", "Francesco Salvi – Esatto", "Ricchi e Poveri – Chi voglio sei tu", "Mia Martini – Almeno tu nell'universo", "Ornella Vanoni – Io come farò", "Gino Paoli – Questa volta no", "Raf – Cosa resterà degli anni ’80"],
        "1990": ["Pooh – Uomini soli", "Toto Cutugno – Gli amori", "Amedeo Minghi y Mietta – Vattene amore", "Anna Oxa – Donna con te", "Marcella y Gianni Bella – Verso l’ignoto", "Mia Martini – La nevicata del ’56", "Mango – Tu…sì", "Francesco Salvi – A", "Caterina Caselli – Bisognerebbe non pensare che a te", "Riccardo Fogli – Ma quale amore", "Paola Turci – Ringrazio Dio"],
        "1991": ["Riccardo Cocciante – Se stiamo insieme", "Renato Zero – Spalle al muro", "Marco Masini – Perché lo fai", "Umberto Tozzi – Gli altri siamo noi", "Pierangelo Bertoli y Tazenda – Spunta la Luna dal monte", "Amedeo Minghi – Nené", "Mietta – Dubbi no", "Al Bano y Romina Power – Oggi sposi", "Raf – Oggi un Dio non ho", "Fiordaliso – Il mare più grande che c'è (I Love You Man)", "Jo Squillo y Sabrina Salerno – Siamo donne"],
        "1992": ["Luca Barbarossa – Portami a ballare", "Mia Martini – Gli uomini non cambiano", "Paolo Vallesi – La forza della vita", "Pierangelo Bertoli – Italia d’oro", "Massimo Ranieri – Ti penso", "Matia Bazar – Piccoli giganti", "Tazenda – Pitzinnos in sa gherra", "Fausto Leali – Perchè", "Riccardo Fogli – In una notte così", "Michele Zarrillo – Strade di Roma"],
        "1993": ["Enrico Ruggeri – Mistero", "Cristiano De André – Dietro la porta", "Rossana Casale y Grazia Di Michele – Gli amori diversi", "Matia Bazar – Dedicato a te", "Renato Zero – Ave Maria", "Mietta y Ragazzi di Via Meda – Figli di chi", "Paola Turci – Stato di calma apparente", "Biagio Antonacci – Non so più a chi credere", "Amedeo Minghi – Notte bella, magnifica", "Loredana Bertè y Mia Martini – Stiamo come stiamo"],
        "1994": ["Aleandro Baldi - Passerà", "Giorgio Faletti - Signor tenente", "Laura Pausini - Strani amori", "Gerardina Trovato - Non è un film", "Michele Zarrillo - Cinque giorni", "Enzo Jannacci y Paolo Rossi - I soliti accordi", "Ivan Graziani - Maledette malelingue", "Andrea Mingardi - Amare amare", "Donatella Rettore - Di notte specialmente", "Mariella Nava - Terra mia", "Loredana Bertè - Amici non ne ho"],
        "1995": ["Giorgia - Come saprei", "Gianni Morandi y Barbara Cola - In amore", "Ivana Spagna - Gente come noi", "Andrea Bocelli - Con te partirò", "Fiorello - Finalmente tu", "Danilo Amerio - Bisogno d'amore", "883 - Senza averti qui", "Mango - Dove vai...", "Toto Cutugno - Voglio andare a vivere in campagna", "Patty Pravo - I giorni dell'armonia"],
        "1996": ["Ron y Tosca - Vorrei incontrarti fra cent'anni", "Elio e le Storie Tese - La terra dei cachi", "Giorgia - Strano il mio destino", "Ivana Spagna - E io penso a te", "Neri per Caso - Mai più sola", "Massimo Di Cataldo - Se adesso te ne vai", "Al Bano - È la mia vita", "Amedeo Minghi - Cantare è d'amore", "Paola Turci - Volo così", "Michele Zarrillo - L'elefante e la farfalla", "Enrico Ruggeri - L'amore è un attimo"],
        "1997": ["Jalisse - Fiumi di parole", "Anna Oxa - Storie", "Syria - Sei tu", "Silvia Salemi - A casa di Luca", "Fausto Leali - Non ami che te", "O.R.O. - Padre Nostro", "Nek - Laura non c'è", "Patty Pravo - ...e dimmi che non vuoi morire", "Massimo Ranieri - Ti parlerò d'amore", "Tosca - Nel respiro più grande", "Marina Rei - Dentro me", "Pitura Freska - Papa nero", "Carmen Consoli - Confusa e felice"],
        "1998": ["Annalisa Minetti – Senza te o con te", "Antonella Ruggiero – Amore lontanissimo", "Lisa – Sempre", "Paola Turci – Solo come me", "Silvia Salemi – Pathos", "Mango y Zenîma – Luce", "Luca Sepe – Un po' di te", "Niccolò Fabi – Lasciarsi un giorno a Roma", "Ron – Un porto nel vento", "Alex Baroni – Sei tu o lei (Quello che voglio)", "Ivana Spagna – E che mai sarà", "Piccola Orchestra Avion Travel – Dormi e sogna", "Paola e Chiara – Per te", "Enzo Jannacci – Quando un musicista ride"],
        "1999": ["Anna Oxa – Senza pietà", "Antonella Ruggiero – Non ti dimentico (Se non ci fossero le nuvole)", "Mariella Nava – Così è la vita", "Enzo Gragnaniello y Ornella Vanoni – Alberi", "Stadio – Lo zaino", "Al Bano – Ancora in volo", "Marina Rei – Un inverno da baciare", "Nino D'Angelo – Senza giacca e cravatta", "Daniele Silvestri – Aria", "Nada – Guardami negli occhi", "Eugenio Finardi – Amami Lara", "Gianluca Grignani – Il giorno perfetto"],
        "2000": ["Piccola Orchestra Avion Travel - Sentimento", "Irene Grandi - La tua ragazza sempre", "Gianni Morandi - Innamorato", "Max Gazzè - Il timido ubriaco", "Samuele Bersani - Replay", "Gerardina Trovato - Gechi e vampiri", "Carmen Consoli - In bianco e nero", "Matia Bazar - Brivido caldo", "Alice - Il giorno dell'indipendenza", "Gigi D'Alessio - Non dirgli mai", "Subsonica - Tutti i miei sbagli", "Ivana Spagna - Con il tuo nome", "Mietta - Fare l'amore", "Marco Masini - Raccontami di te"],
        "2001": ["Elisa - Luce (tramonti a nord est)", "Giorgia - Di sole e d'azzurro", "Matia Bazar - Questa nostra grande storia d'amore", "Michele Zarrillo - L'acrobata", "Paola Turci - Saluto l'inverno", "Jenny B - Anche tu", "Alex Britti - Sono contento", "Gigi D'Alessio - Tu che ne sai", "Anna Oxa - L'eterno movimento", "Syria - Fantasticamenteamore", "Bluvertigo - L'assenzio (The Power of Nothing)"],
        "2002": ["Matia Bazar - Messaggio d'amore", "Alexia - Dimmi come…", "Gino Paoli - Un altro amore", "Fausto Leali y Luisa Corna - Ora che ho bisogno di te", "Enrico Ruggeri - Primavera a Sarajevo", "Mariella Nava - Il cuore mio", "Francesco Renga - Tracce di te", "Fiordaliso - Accidenti a te", "Gianluca Grignani - Lacrime dalla Luna", "Daniele Silvestri - Salirò", "Patty Pravo - L'immenso", "Loredana Bertè - Dimmi che mi ami"],
        "2003": ["Alexia – Per dire di no", "Alex Britti – 7000 caffè", "Sergio Cammariere – Tutto quello che un uomo", "Enrico Ruggeri y Andrea Mirò – Nessuno tocchi Caino", "Syria – L'amore è", "Lisa – Oceano", "Giuni Russo – Morirò d'amore", "Silvia Salemi – Nel cuore delle donne", "Antonella Ruggiero – Di un amore", "Luca Barbarossa – Fortuna", "Fausto Leali – Eri tu", "Anna Oxa – Cambierò", "Negrita – Tonight"],
        "2004": ["Marco Masini – L'uomo volante", "Mario Rosini – Sei la vita mia", "Linda – Aria, sole, terra e mare", "Paolo Meneguzzi – Guardami negli occhi (prego)", "Bungaro – Guardastelle", "Neﬀa – Le ore piccole", "Mario Venuti – Crudele", "DJ Francesco – Era bellissimo", "Piotta – Ladro di te"],
        "2005": ["Francesco Renga – Angelo", "Toto Cutugno y Annalisa Minetti – Come noi nessuno al mondo", "Antonella Ruggiero – Echi d'infinito", "Nicky Nicolai y Stefano Di Battista Jazz Quartet – Che mistero è l'amore", "Laura Bono – Non credo nei miracoli", "Marcella Bella – Uomo bastardo", "Anna Tatangelo – Ragazza di periferia", "Alexia – Da grande", "Matia Bazar – Grido d'amore", "Gigi D'Alessio – L'amore che non c'è", "Le Vibrazioni – Ovunque andrò", "Negramaro – Mentre tutto scorre", "Modà - Riesci a innamorarmi"],
        "2006": ["Povia – Vorrei avere il becco", "Nomadi – Dove si va", "Anna Tatangelo – Essere una donna", "Riccardo Maﬀoni – Sole negli occhi", "Simone Cristicchi – Che bella gente", "Dolcenera – Com'è straordinaria la vita", "Michele Zarrillo – L'alfabeto degli amanti", "Zero Assoluto – Svegliarsi la mattina", "Ron – L'uomo delle stelle", "Alex Britti – Solo con te", "Ivana Spagna – Noi non possiamo cambiare", "Gianluca Grignani – Liberi di sognare", "Anna Oxa – Processo a me stessa"],
        "2007": ["Simone Cristicchi – Ti regalerò una rosa", "Al Bano – Nel perdono", "Piero Mazzocchetti – Schiavo d'amore", "Daniele Silvestri – La paranza", "Mango – Chissà se nevica", "Paolo Meneguzzi – Musica", "Tosca – Il terzo fuochista", "Zero Assoluto – Appena prima di partire", "Antonella Ruggiero – Canzone fra le guerre", "Stadio – Guardami", "Nada – Luna in piena", "Johnny Dorelli – Meglio così", "Milva – The Show Must Go On"],
        "2008": ["Giò Di Tonno y Lola Ponce – Colpo di fulmine", "Anna Tatangelo – Il mio amico", "Fabrizio Moro – Eppure mi hai cambiato la vita", "Toto Cutugno – Un falco chiuso in gabbia", "Finley – Ricordi", "Paolo Meneguzzi – Grande", "Sergio Cammariere – L'amore non si spiega", "Gianluca Grignani – Cammina nel sole", "Little Tony – Non finisce qui", "Max Gazzè – Il solito sesso", "L'Aura – Basta!", "Frankie hi-nrg mc – Rivoluzione", "Tricarico – Vita tranquilla", "Tiromancino – Il rubacuori", "Loredana Bertè – Musica e parole (descalificada)"],
        "2009": ["Marco Carta - La forza mia", "Povia - Luca era gay", "Sal Da Vinci - Non riesco a farti innamorare", "Francesco Renga - Uomo senza età", "Marco Masini - L'Italia", "Patty Pravo - E io verrò un giorno là", "Alexia y Mario Lavezzi - Biancaneve", "Al Bano - L'amore è sempre amore", "Dolcenera - Il mio amore unico", "Afterhours - Il paese è reale", "Iva Zanicchi - Ti voglio senza amore"],
        "2010": ["Valerio Scanu - Per tutte le volte che...", "Pupo y Emanuele Filiberto con Luca Canonici - Italia amore mio", "Marco Mengoni - Credimi ancora", "Noemi - Per tutta la vita", "Malika Ayane - Ricomincio da qui", "Irene Fornaciari y Nomadi - Il mondo piange", "Simone Cristicchi - Meno male", "Irene Grandi - La cometa di Halley", "Arisa - Malamorenò", "Povia - La verità"],
        "2011": ["Roberto Vecchioni - Chiamami ancora amore", "Modà y Emma - Arriverà", "Al Bano - Amanda è libera", "Davide Van De Sfroos - Yanez", "Luca Madonia y Franco Battiato - L'alieno", "La Crus - Io confesso", "Nathalie - Vivo sospesa", "Luca Barbarossa y Raquel del Rosario - Fino in fondo", "Anna Tatangelo - Bastardo", "Giusy Ferreri - Il mare immenso", "Patty Pravo - Il vento e le rose", "Anna Oxa - La mia anima d'uomo"],
        "2012": ["Emma - Non è l'inferno", "Arisa - La notte", "Noemi - Sono solo parole", "Gigi D'Alessio y Loredana Bertè - Respirare", "Pierdavide Carone y Lucio Dalla - Nanì", "Dolcenera - Ci vediamo a casa", "Nina Zilli - Per sempre", "Francesco Renga - La tua bellezza", "Samuele Bersani - Un pallone", "Eugenio Finardi - E tu lo chiami Dio"],
        "2013": ["Marco Mengoni - L'essenziale", "Elio e le Storie Tese - La canzone mononota", "Modà - Se si potesse non morire", "Malika Ayane - E se poi", "Raphael Gualazzi - Sai (ci basta un sogno)", "Daniele Silvestri - A bocca chiusa", "Max Gazzè - Sotto casa", "Chiara - Il futuro che sarà", "Annalisa - Scintille", "Maria Nazionale - È colpa mia", "Simone Cristicchi - La prima volta (che sono morto)"],
        "2014": ["Arisa - Controvento", "Raphael Gualazzi & The Bloody Beetroots - Liberi o no", "Renzo Rubino - Ora", "Francesco Renga - Vivendo adesso", "Noemi - Bagnati dal sole", "Perturbazione - L'unica", "Cristiano De André - Il cielo è vuoto", "Frankie hi-nrg mc - Pedala", "Giusy Ferreri - Ti porto a cena con me", "Francesco Sarcina - Nel tuo sorriso", "Ron - Sing in the rain", "Riccardo Sinigallia - Prima di andare via (descalificado)"],
        "2015": ["Il Volo - Grande amore", "Nek - Fatti avanti amore", "Malika Ayane - Adesso e qui (nostalgico presente)", "Annalisa - Una finestra tra le stelle", "Chiara - Straordinario", "Marco Masini - Che giorno è", "Dear Jack - Il mondo esplode tranne noi", "Gianluca Grignani - Sogni infranti", "Nina Zilli - Sola", "Lorenzo Fragola - Siamo uguali", "Alex Britti - Un attimo importante", "Irene Grandi - Un vento senza nome", "Nesli - Buona fortuna amore", "Anna Tatangelo - Libera", "Lara Fabian - Voce"],
        "2016": ["Stadio - Un giorno mi dirai", "Francesca Michielin - Nessun grado di separazione", "Giovanni Caccamo y Deborah Iurato - Via da qui", "Enrico Ruggeri - Il primo amore non si scorda mai", "Lorenzo Fragola - Infinite volte", "Patty Pravo - Cieli immensi", "Clementino - Quando sono lontano", "Noemi - La borsa di una donna", "Rocco Hunt - Wake Up", "Arisa - Guardando il cielo", "Annalisa - Il diluvio universale", "Elio e le Storie Tese - Vincere l'odio", "Valerio Scanu - Finalmente piove", "Alessio Bernabei - Noi siamo infinito", "Dolcenera - Ora o mai più (le cose cambiano)"],
        "2017": ["Francesco Gabbani - Occidentali's Karma", "Fiorella Mannoia - Che sia benedetta", "Ermal Meta - Vietato morire", "Michele Bravi - Il diario degli errori", "Paola Turci - Fatti bella per te", "Sergio Sylvestre - Con te", "Fabrizio Moro - Portami via", "Elodie - Tutta colpa mia", "Bianca Atzei - Ora esisti solo tu", "Samuel - Vedrai", "Michele Zarrillo - Mani nelle mani", "Lodovica Comello - Il cielo non mi basta", "Marco Masini - Spostato di un secondo", "Chiara - Nessun posto è casa mia", "Clementino - Ragazzi fuori", "Al Bano - Di rose e di spine", "Gigi D'Alessio - La prima stella"],
        "2018": ["Ermal Meta y Fabrizio Moro - Non mi avete fatto niente", "Lo Stato Sociale - Una vita in vacanza", "Annalisa - Il mondo prima di te", "Ron - Almeno pensami", "Ornella Vanoni con Bungaro y Paciﬁco - Imparare ad amarsi", "Max Gazzè - La leggenda di Cristalda e Pizzomunno", "Luca Barbarossa - Passame er sale", "Diodato y Roy Paci - Adesso", "The Kolors - Frida (mai, mai, mai)", "Giovanni Caccamo - Eterno", "Le Vibrazioni - Così sbagliato", "Enzo Avitabile y Peppe Servillo - Il coraggio di ogni giorno", "Noemi - Non smettere mai di cercarmi", "Nina Zilli - Senza appartenere", "Elio e le Storie Tese - Arrivedorci"],
        "2019": ["Mahmood - Soldi", "Ultimo - I tuoi particolari", "Il Volo - Musica che resta", "Loredana Bertè - Cosa ti aspetti da me", "Simone Cristicchi - Abbi cura di me", "Daniele Silvestri y Rancore - Argentovivo", "Irama - La ragazza con il cuore di latta", "Arisa - Mi sento bene", "Achille Lauro - Rolls Royce", "Enrico Nigiotti - Nonno Hollywood", "Boomdabash - Per un milione", "Ghemon - Rose viola", "Ex-Otago - Solo una canzone", "Motta - Dov'è l'Italia", "Francesco Renga - Aspetto che torni", "Nek - Mi farò trovare pronto", "The Zen Circus - L'amore è una dittatura", "Patty Pravo y Briga - Un po' come la vita"],
        "2020": ["Diodato - Fai rumore", "Francesco Gabbani - Viceversa", "Pinguini Tattici Nucleari - Ringo Starr", "Le Vibrazioni - Dov'è", "Piero Pelù - Gigante", "Tosca - Ho amato tutto", "Elodie - Andromeda", "Achille Lauro - Me ne frego", "Irene Grandi - Finalmente io", "Rancore - Eden", "Raphael Gualazzi - Carioca", "Levante - Tikibombom", "Anastasio - Rosso di rabbia", "Alberto Urso - Il sole ad est", "Marco Masini - Il confronto", "Rita Pavone - Niente (Resilienza 74)", "Michele Zarrillo - Nell'estasi o nel fango", "Elettra Lamborghini - Musica (e il resto scompare)", "Bugo e Morgan - Sincero (descalificado)"],
        "2021": ["Måneskin - Zitti e buoni", "Francesca Michielin y Fedez - Chiamami per nome", "Ermal Meta - Un milione di cose da dirti", "Colapesce Dimartino - Musica leggerissima", "Irama - La genesi del tuo colore", "Willie Peyote - Mai dire mai (la locura)", "Annalisa - Dieci", "Madame - Voce", "Orietta Berti - Quando ti sei innamorato", "Arisa - Potevi fare di più", "La Rappresentante di Lista - Amare", "Extraliscio y Davide Toﬀolo - Bianca luce nera", "Lo Stato Sociale - Combat pop", "Noemi - Glicine", "Malika Ayane - Ti piaci così", "Max Gazzè - Il farmacista", "Coma_Cose - Fiamme negli occhi", "Francesco Renga - Quando trovo te", "Bugo - E invece sì"],
        "2022": ["Mahmood e Blanco - Brividi", "Elisa - O forse sei tu", "Gianni Morandi - Apri tutte le porte", "Irama - Ovunque sarai", "Sangiovanni - Farfalle", "Emma - Ogni volta è così", "La Rappresentante di Lista - Ciao ciao", "Massimo Ranieri - Lettera di là dal mare", "Dargen D'Amico - Dove si balla", "Michele Bravi - Inverno dei ﬁori", "Matteo Romano - Virale", "Fabrizio Moro - Sei tu", "Achille Lauro con Harlem Gospel Choir - Domenica", "Noemi - Ti amo non lo so dire", "Ditonellapiaga e Rettore - Chimica", "Rkomi - Insuperabile", "Iva Zanicchi - Voglio amarti", "Le Vibrazioni - Tantissimo", "Giusy Ferreri - Miele", "Ana Mena - Duecentomila ore", "Tananai - Sesso occasionales"],
        "2023": ["Marco Mengoni - Due vite", "Lazza - Cenere", "Mr. Rain - Supereroi", "Ultimo - Alba", "Tananai - Tango", "Giorgia - Parole dette male", "Madame - Il bene nel male", "Rosa Chemical - Made in Italy", "Elodie - Due", "Colapesce Dimartino - Splash", "Modà - Lasciami", "Gianluca Grignani - Quando ti manca il ﬁato", "Coma_Cose - L'addio", "Ariete - Mare di guai", "Articolo 31 - Un bel viaggio", "Paola & Chiara - Furore", "Leo Gassmann - Terzo cuore", "Mara Sattei - Duemilaminuti", "Cugini di Campagna - Lettera 22", "Levante - Vivo", "Anna Oxa - Sali (canto dell'anima)"],
        "2024": ["Angelina Mango - La noia", "Geolier - I p' me, tu p' te", "Annalisa - Sinceramente", "Ghali - Casa mia", "Irama - Tu no", "Mahmood - Tuta gold", "Loredana Bertè - Pazza", "Il Volo - Capolavoro", "Alessandra Amoroso - Fino a qui", "Alfa - Vai!", "Gazzelle - Tutto qui", "Il Tre - Fragili", "Diodato - Ti muovi", "Emma - Apnea", "Fiorella Mannoia - Mariposa", "The Kolors - Un ragazzo una ragazza", "Mr. Rain - Due altalene", "Santi Francesi - L'amore in bocca", "Negramaro - Ricominciamo tutto", "Dargen D'Amico - Onda alta", "Ricchi e Poveri - Ma non tutta la vita", "BigMama - La rabbia non ti basta", "Rose Villain - Click boom!", "Clara - Diamanti grezzi", "Renga Nek - Pazzo di te", "Sangiovanni - Finiscimi", "Fred De Palma - Il cielo non ci vuole"],
        "2025": ["Olly - Balorda nostalgia", "Lucio Corsi - Volevo essere un duro", "Brunori Sas - L'albero delle noci", "Fedez - Battito", "Simone Cristicchi - Quando sarai piccola", "Giorgia - La cura per me", "Achille Lauro - Incoscienti giovani", "Francesco Gabbani - Viva la vita", "Irama - Lentamente", "Coma_Cose - Cuoricini", "Bresh - La tana del granchio", "Elodie - Dimenticarsi alle 7", "Noemi - Se t'innamori muori", "The Kolors - Tu con chi fai l'amore", "Rocco Hunt - Mille vote ancora", "Willie Peyote - Grazie ma no grazie", "Sarah Toscano - Amarcord", "Shablo con Guè, Joshua e Tormento - La mia parola", "Rose Villain - Fuorilegge", "Joan Thiele - Eco", "Francesca Michielin - Fango in paradiso", "Modà - Non ti dimentico", "Massimo Ranieri - Tra le mani un cuore", "Serena Brancale - Anema e core", "Tony Eﬀe - Damme 'na mano", "Gaia - Chiamo io chiami tu", "Clara - Febbre", "Rkomi - Il ritmo delle cose", "Marcella Bella - Pelle diamante", "Emis Killa - Demoni (descalificado)"]
    };

    // --- VARIABLES Y CONSTANTES DEL DOM ---
    const votingSectionsContainer = document.getElementById('voting-sections');
    const prevBtn = document.getElementById('prev-btn');
    const nextBtn = document.getElementById('next-btn');
    const userInfo = document.getElementById('user-info');
    const form = document.getElementById('sanremo-form');
    const sectionTitle = document.getElementById('section-title');
    const navButtons = document.getElementById('navigation-buttons');

    let currentSection = 0;
    const totalSections = 10;
    const points = [1, 2, 3, 4, 5, 6, 7, 8, 10, 12];

    // --- FUNCIÓN PARA CREAR LAS SECCIONES DE VOTACIÓN ---
    function createVotingSections() {
        let allSectionsHTML = '';
        for (let i = 0; i < totalSections; i++) {
            allSectionsHTML += `
                <div class="voting-section ${i === 0 ? '' : 'hidden'}" id="section-${i}">
                    <label for="year-${i}">Año:</label>
                    <select id="year-${i}" name="year-${i}" required>
                        <option value="">Selecciona un año</option>
                        ${Object.keys(songsData).sort((a,b) => b-a).map(year => `<option value="${year}">${year}</option>`).join('')}
                    </select>
                    
                    <label for="song-${i}">Canción:</label>
                    <select id="song-${i}" name="song-${i}" required>
                        <option value="">Primero selecciona un año</option>
                    </select>
                </div>
            `;
        }
        votingSectionsContainer.innerHTML = allSectionsHTML;
    }

    // --- FUNCIÓN PARA ACTUALIZAR LAS CANCIONES SEGÚN EL AÑO ---
    function updateSongs(yearSelect, songSelect) {
        const selectedYear = yearSelect.value;
        songSelect.innerHTML = '<option value="">Selecciona una canción</option>'; // Limpiar y poner placeholder
        if (selectedYear && songsData[selectedYear]) {
            songsData[selectedYear].forEach(song => {
                const option = document.createElement('option');
                option.value = song;
                option.textContent = song;
                songSelect.appendChild(option);
            });
        }
    }
    
    // --- FUNCIÓN PARA MOSTRAR LA SECCIÓN ACTUAL ---
    function showSection(index) {
        document.querySelectorAll('.voting-section').forEach((section, i) => {
            section.classList.toggle('hidden', i !== index);
        });

        // Actualizar título y visibilidad de botones
        sectionTitle.textContent = `Votación ${index + 1} (${points[index]} puntos)`;
        prevBtn.classList.toggle('hidden', index === 0);
        
        if (index === totalSections - 1) {
            nextBtn.classList.add('hidden');
            userInfo.classList.remove('hidden');
            navButtons.classList.add('hidden');
        } else {
            nextBtn.classList.remove('hidden');
            userInfo.classList.add('hidden');
            navButtons.classList.remove('hidden');
        }
    }

    // --- INICIALIZACIÓN Y EVENT LISTENERS ---
    createVotingSections();

    // Añadir listeners a todos los select de año
    for (let i = 0; i < totalSections; i++) {
        const yearSelect = document.getElementById(`year-${i}`);
        const songSelect = document.getElementById(`song-${i}`);
        yearSelect.addEventListener('change', () => updateSongs(yearSelect, songSelect));
    }

    nextBtn.addEventListener('click', () => {
        if (currentSection < totalSections - 1) {
            currentSection++;
            showSection(currentSection);
        }
    });

    prevBtn.addEventListener('click', () => {
        if (currentSection > 0) {
            currentSection--;
            showSection(currentSection);
        }
    });

    form.addEventListener('submit', function(e) {
        e.preventDefault();
        const submitButton = document.getElementById('submit-btn');
        submitButton.disabled = true;
        submitButton.textContent = 'Enviando...';

        // ===================================================================
        // IMPORTANTE: REEMPLAZA ESTA URL CON LA TUYA DE GOOGLE APPS SCRIPT
        const scriptURL = 'URL_DE_TU_SCRIPT_DE_GOOGLE_APPS';
        // ===================================================================
        
        fetch(scriptURL, { method: 'POST', body: new FormData(form)})
            .then(response => {
                alert('¡Votos enviados con éxito!');
                form.reset();
                currentSection = 0;
                // Resetear todos los select de canciones
                 for (let i = 0; i < totalSections; i++) {
                    document.getElementById(`song-${i}`).innerHTML = '<option value="">Primero selecciona un año</option>';
                 }
                showSection(currentSection); // Volver al inicio
                submitButton.disabled = false;
                submitButton.textContent = 'Enviar Votos';
            })
            .catch(error => {
                console.error('Error!', error.message);
                alert('Hubo un error al enviar tus votos. Por favor, inténtalo de nuevo.');
                submitButton.disabled = false;
                submitButton.textContent = 'Enviar Votos';
            });
    });

    // Mostrar la primera sección al cargar
    showSection(0);
});